/**
 * Plura P Javascript Framework [http://plura.pt]
 * 
 * Copyright (c) 2014 Plura
 *
 * Date: 2014-03-18 12:00:00 (Tue, 18 Mar 2014)
 * Revision: 6246
 */
var plura=plura||{};plura.constants={PHP:$('script[src$="p.js"]').length?$('script[src$="p.js"]')[0].src.replace(/p\.js$/,"p.php"):null,REGEX_EMAIL:/^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/,SWF:$('script[src$="p.js"]').length?$('script[src$="p.js"]')[0].src.replace(/p\.js$/,"p.swf"):null};plura=plura||{};plura.core=plura.core||{};
plura.core.Loader=function(e){var b,d,c,a,f,k,g,h=function(a){"img"===a.dataType?(d[a.name]=$(new Image),d[a.name].error(function(){b.trigger("LOADER_ERROR",l())}).load(function(){m(d[a.name])}).prop({src:a.path})):$.ajax({url:a.path,dataType:a.dataType,type:a.type,success:function(b){d[a.name]=b;m(d[a.name])},error:function(a,d,g){b.trigger("LOADER_ERROR",l())}})},m=function(d){a[c]=d;k=Math.ceil((c+1)/g.length*100);b.trigger("LOADER_COMPLETE_ITEM",l());c<g.length-1?(c+=1,q(c)):b.trigger("LOADER_COMPLETE",
l())},l=function(){return{content:d,index:c,items:a,item:$.extend({},g[c],{obj:d[g[c].name]}),progress:k}},q=function(a){h(g[a]);b.trigger("LOADER_CHANGE",l())};f=$.extend(!0,{},{data:null,cache:!1,log:!1},e);b=f.target||$(window);d={};a=[];c=0;g=function(a){var b=$.extend([],a);for(a=0;a<b.length;a+=1)b[a].dataType||(b[a].path.match(/\.(jpg|png|gif)$/i)?b[a].dataType="img":b[a].dataType="text"),b[a].label||(b[a].label=b[a].path.match(/.*\/(.*\..*)$/)[1]),b[a].type||(b[a].type="GET"),f.cache||(b[a].path=
plura.utils.Cache(b[a].path),console.log(plura.utils.Cache(b[a].path)));return b}(f.data);this.core=b;this.data=d;this.items=a;q(c);return this};plura=plura||{};plura.event=plura.event||{};
plura.event.Touch=function(e){var b,d,c,a,f,k,g,h,m,l=function(){g=k=f=a=c=d=0;m=h=null};b=$.extend(!0,{},{length:72,target:null},e);this.core=b.target;l();b.target.on("MSPointerDown MSPointerMove MSPointerUp MSPointerOver MSPointerOut touchstart touchend touchmove touchcancel",function(e){e.stopImmediatePropagation();switch(e.type){case "MSPointerUp":case "touchend":e.preventDefault();if(1===d&&0!==f){g=Math.round(Math.sqrt(Math.pow(f-c,2)+Math.pow(k-a,2)));if(g>=b.length){e=c-f;var r=k-a;Math.round(Math.sqrt(Math.pow(e,
2)+Math.pow(r,2)));e=Math.atan2(r,e);h=Math.round(180*e/Math.PI);0>h&&(h=360-Math.abs(h));m=45>=h&&0<=h?"left":360>=h&&315<=h?"left":135<=h&&225>=h?"right":45<h&&135>h?"down":"up"}b.target.trigger("TOUCHSWIPE",{direction:g>=b.length?m:!1})}l();break;case "touchcancel":l();break;case "MSPointerMove":case "touchmove":e.preventDefault();e.originalEvent.touches&&1!==e.originalEvent.touches.length?l():(f=e.originalEvent.pageX||e.originalEvent.touches[0].pageX,k=e.originalEvent.pageY||e.originalEvent.touches[0].pageY,
b.target.trigger("TOUCHMOVE",{delta:{x:c-f,y:a-k},position:{x:f,y:k}}));break;case "MSPointerDown":case "touchstart":e.preventDefault(),d=e.originalEvent.touches?e.originalEvent.touches.length:1,1===d?(c=e.originalEvent.pageX||e.originalEvent.touches[0].pageX,a=e.originalEvent.pageY||e.originalEvent.touches[0].pageY):l()}})};plura=plura||{};plura.form=plura.form||{};
plura.form.Form=function(e){var b,d,c,a,f=function(a){var d=b.find("*[name="+a.name+"]"),c;switch(a.type){case "list":case "select":for(d.empty(),"select"===a.type&&d.append("<option/>"),c=0;c<a.values.length;c+=1)$("<option/>").prop({value:void 0!==a.values[c].value?a.values[c].value:a.values[c][a.name]}).appendTo(d).html(a.values[c].label||a.values[c].name||a.values[c].value)}a.value&&d.val(a.value)},k=function(d,h){var e,l,q=d||(c.submit?c.fields.concat([{type:"submit",value:c.submit}]):c.fields);
for(e=0;e<q.length;e+=1)if(q[e]instanceof Array||q[e].fields||q[e].type&&q[e].type.match(/^(field)?set$/i))l=$("<fieldset/>").appendTo(h||b).prop({name:q[e].name}),q[e]instanceof Array||$("<legend/>").appendTo(l).text(q[e].label||q[e].name),k(q[e].fields||q[e],l);else{l=q[e];var r=h||b,n=void 0,p=void 0;$("<div/>");var s=n=void 0;switch(l.type){case "select":n=$("<select/>");break;case "list":n=$("<select/>").prop({multiple:!0,size:l.size||1});break;case "textarea":n=$("<textarea/>");l.wysiwyg&&window.tinyMCE&&
(p=tinymce.DOM.uniqueId(),s=$.extend(!0,c.tinyMCE,{editor_selector:p},"number"!==typeof l.wysiwyg?l.wysiwyg:null,{width:300}),n.addClass(p+" tinyMCE").prop({id:p}).appendTo("body").width(n.width()).height(n.height()),tinyMCE.init(s));break;case "file":n=new plura.form.Upload($.extend({name:l.name,target:r},c.upload));break;default:n=l.type&&"date"!==l.type?l.type:"text",n=$("<input/>").prop({type:n}),jQuery.ui&&"date"===l.type&&n.datepicker({dateFormat:"yy-mm-dd"})}l.disabled&&n.prop({disabled:"disabled"});
l.change&&n.change(l.change);l.label&&$("<label/>").text(l.label||l.name).appendTo(r).prop({"for":l.name});l.type&&l.type.match(/file/)||n.prop({name:l.name}).appendTo(r);l.type&&l.type.match(/file/)&&a.push(n);void 0===l.value&&!l.values||l.type&&!l.type.match(/(checkbox|list|select|submit|radio|text|textarea)/)||(l.type&&l.type.match(/(checkbox|radio|submit)/)?(n.prop({value:l.value}),l.type.match(/(checkbox|radio)/)&&l.checked&&n.prop("checked",!0)):f(l))}};this._query=function(){return d._query()};
this._params=function(a){return d._params(a)};this.populate=function(a){var d,c;for(d in a)if(a.hasOwnProperty(d)&&(c=b.find("*[name="+d+"]"),c.length))switch(c.prop("type")){case "checkbox":c.prop("checked","0"!==a[d]);break;default:c[0].tagName.match(/textarea/i)&&c.hasClass("tinyMCE")?tinyMCE.get(c.prop("id")).setContent(a[d]||""):c.val(a[d])}};this.refresh=function(a){for(var b in c.fields)c.fields.hasOwnProperty(b)&&a[c.fields[b].name]&&f($.extend(!0,{},c.fields[b],{values:a[c.fields[b].name]}))};
this.reset=function(a){d.reset(a)};c=$.extend(!0,{},{alert:{success:"Success! Content updated!",error:"Error! Content not updated! :("},check:null,fields:null,path:null,params:null,reset:!1,send:!0,submit:"Submit",tinyMCE:{mode:"specific_textareas",theme:"advanced",plugins:"fullscreen",theme_advanced_buttons1:"bold,italic,underline,|,strikethrough,justifyleft,justifycenter,justifyright,justifyfull,|,bullist,numlist,outdent,indent",theme_advanced_buttons2:"formatselect,sub,sup,code,fullscreen,link,unlink,|,forecolor,removeformat"}},
e);b=$("<form/>").appendTo(c.target);a=[];k();this.core=b;this.uploads=a;d=new plura.form.FormManager($.extend(!0,{},{ajax:c.ajax||{},alert:c.alert||{},check:c.check||{},params:c.params||{}},{path:c.path,reset:c.reset,send:c.send,target:this,type:"getJSON"}));return this};(function(){Object.defineProperties(plura.form.Form.prototype,{query:{get:function(){return this._query()}},params:{get:function(){return this._params()},set:function(e){this._params(e)}}})})();plura=plura||{};
plura.form=plura.form||{};
plura.form.FormManager=function(e){var b,d,c,a=function(a){b.find("input[type=file]").each(function(d){c[d]=new plura.form.Upload($.extend({name:$(this).attr("name"),target:b},a));c[d].core.replaceAll($(this))})},f=function(a){var d=$.extend({},{not:":button, :submit, :reset",checked:!0,selected:!0,upload:!0}),e=b.find(":input").not(d.not);e.not(":checkbox, :radio").val("");d.checked&&e.prop("checked",!1);d.selected&&e.prop("selected",!1);for(d=0;d<c.length;d+=1)c[d].reset(a);window.tinyMCE&&b.find(".tinyMCE").each(function(){tinymce.get($(this).prop("id")).setContent("");
tinymce.get($(this).prop("id")).nodeChanged()})},k=function(){var a=d.path||window.location.href,c=function(a,d){return"string"===typeof a?a:a.alert?a:$.extend(!0,{},a,{alert:d})};console&&console.log(d.ajax.dataType+" | "+d.ajax.type+" | "+a+":"+g());$.ajax({url:a,data:g(),dataType:d.ajax.dataType,type:d.ajax.type,success:function(a){b.trigger("FORM_REQUEST_SUCCESS",c(a,d.alert.complete));!a.success||"true"!==a.success&&1!==a.success?(a.success&&"false"===a.success||0===a.success)&&b.trigger("FORM_PROCESS_ERROR",
c(a,d.alert.error)):(d.reset&&f(!0),b.trigger("FORM_PROCESS_SUCCESS",c(a,d.alert.success)))},error:function(a,d,c){b.trigger("FORM_REQUEST_ERROR",{xhr:a,textStatus:d,errorThrown:c,alert:c})}});b.trigger("FORM_SUBMIT",{alert:d.alert.submit})},g=function(){return b.serialize()+"&"+$.param(d.params||{})};this._query=g;this._params=function(a){void 0!==a&&(d.params=$.extend(!0,d.params||{},a));return d.params};this.reset=f;d=$.extend(!0,{},{ajax:{dataType:"json",type:"GET"},alert:{complete:"Your form was submited.",
error:"There was an error processing your form.",field:"Please correctly fill the % field. Thank you",submit:"Form is being submitted. Please wait.",success:"Your form was successfully processed! Thank you."},check:!1,params:null,path:null,replace:!0,reset:!1,send:!0,target:null,upload:{}},e);b=d.target.core||d.target;c=d.target.uploads||[];this.form=b;d.replace&&a(d.upload);b.submit(function(a){a.preventDefault();window.tinyMCE&&tinyMCE.triggerSave();if(!(a=!d.check))a:{var c,e,g,f;for(c=0;c<d.check.length;c+=
1)for(a=d.check[c],g=a.rules?a.rules instanceof Array?a.rules:[a.rules]:[{alert:a.alert||null}],e=0;e<g.length;e+=1)if(f=plura.utils.String.test([/\./,/#/],a.id)?b.find(a.id):b.find("*[name="+a.id+"]"),g[e].exp&&!plura.utils.String.test(g[e].exp,f.val())||!g[e].exp&&f.val().match(/^\s*$/)){a=g[e].alert||d.alert.field.replace(/%/,a.id);b.trigger("FORM_VALIDATION_ERROR",{alert:a});a=!1;break a}b.trigger("FORM_VALIDATION_SUCCESS");a=!0}a&&d.send&&k()}).find("input[type=reset]").click(function(a){a.preventDefault();
f()})};(function(){Object.defineProperties(plura.form.FormManager.prototype,{query:{get:function(){return this._query()}},params:{get:function(){return this._params()},set:function(e){this._params(e)}}})})();plura=plura||{};plura.form=plura.form||{};plura.form.upload=plura.form.upload||{};
plura.form.upload.File=function(e){var b,d,c,a,f,k,g=function(){d.slideUp("slow",l);k.reset()},h=function(a){$.getJSON(f.process,{action:"delete",file:c.file,path:f.path,type:"upload"},function(b){"true"===b.success&&a&&(g(),d.trigger("FORM_UPLOAD_REMOVE"))})},m=function(a){if(c&&!a)h(!0);else if(!c||c&&a)c||(swf.cancel(f.id),d.trigger("FORM_UPLOAD_CANCEL")),g()},l=function(){$(this).remove()};this.update=function(g){c=g;a=a||$("<input/>").prop({type:"hidden",name:e.name+"[]"}).appendTo(d);a.val(g.file+
"|"+g.name);b.val(f.label.remove)};this.clean=function(){c&&h();b.val(f.label.cancel)};this.reset=m;this.refresh=function(a){k.refresh(a)};f=$.extend(!0,{},{css:{button:{border:"none","float":"right","text-align":"center",width:50},file:{"float":"left",width:"100%"},progress:{"float":"left"}},height:20,label:{cancel:"Cancel",remove:"Delete"},margin:5,swf:null,width:100},e);d=$("<div/>").addClass("file i"+f.id).appendTo(f.target);k=new plura.layout.ProgressBar({target:d,css:{core:$.extend({},f.css.file,
{width:f.width-3*f.margin-f.css.button.width})}});b=$("<input/>").prop({type:"button"}).val(f.label.cancel).addClass("delete").appendTo(d).click(function(a){m()});this.core=d;d.css($.extend({},f.css.file,{"margin-bottom":f.margin}));b.css($.extend({},f.css.button,{height:f.height}));return this};plura=plura||{};plura.form=plura.form||{};
plura.form.Upload=function(e){var b,d,c,a,f,k,g,h=function(){b.children(".files").slideUp("slow",function(){$(this).remove()})},m=function(a){if(d){for(var b in d)d.hasOwnProperty(b)&&(d[b].reset(a),delete d[b]);d=null}h()},l=function(a){a.stopImmediatePropagation();1===b.children(".files").children().length&&m()},q=function(a){var d=$("<div/>");f=swfobject.getObjectById(a.id);d.replaceAll(b);$("body").prepend(b);$("#"+a.id).css({left:k.position().left,position:"absolute",top:k.position().top,zIndex:100});
b.replaceAll(d)},r=function(a,d,b){"true"===b.success&&g.instances["i"+a].update(d,b)},n=function(a,d){g.instances["i"+a].init(d)},p=function(a,d,b){g.instances["i"+a].refresh(d,b)},s=function(a){};this.init=function(c){a.multiple||!a.multiple&&!d?(d=d||{},d["i"+c]=new plura.form.upload.File($.extend(!0,{},a.file,{id:c,name:a.name,path:plura.utils.String.path(a.path,a.process||plura.constants.PHP),process:a.process||plura.constants.PHP,swf:f,target:b.children(".files").length?b.children(".files"):
$("<div/>").appendTo(b).addClass("files").css($.extend({},a.css.files,{"margin-top":a.margin,padding:a.margin+"px "+a.margin+"px 0 "+a.margin+"px",width:a.width-2*a.margin})),width:a.width})),d["i"+c].core.on("FORM_UPLOAD_CANCEL FORM_UPLOAD_REMOVE",l)):!a.multiple&&d&&d["i"+c].clean()};this.refresh=function(a,b){d["i"+a].refresh(b)};this.reset=m;this.update=function(a,b){d["i"+a].update(b)};g=plura.form.upload;g.count=void 0===g.count?0:g.count+1;g.instances=g.instances||{};g.instances["i"+g.count]=
this;g.complete=g.complete||r;g.init=g.init||n;g.refresh=g.refresh||p;g.test=g.test||s;c=g.count;a=$.extend(!0,{},{css:{files:{"float":"left","background-color":"#e0e0e0"},progress:{"float":"left"},trigger:{border:"none","float":"right","text-align":"center",width:70}},file:{},label:{cancel:"Cancel",remove:"Delete",upload:"Upload"},height:30,limit:0,margin:5,multiple:!1,path:"",obj:"plura.form.upload",swf:{params:{allowscriptaccess:"always",menu:"false",wmode:"transparent"},version:"10.0"},process:null,
width:220},e);b=$("<div/>").css({position:"relative"}).addClass("upload i"+c).appendTo(a.target);new plura.layout.ProgressBar({target:b,css:{core:$.extend({},a.css.progress,{width:a.width-a.css.trigger.width-a.margin,height:a.height})}});k=$("<input/>").prop({type:"button",value:a.label.upload}).addClass("trigger").appendTo(b);this.core=b;b.css({width:a.width});k.css($.extend({},a.css.trigger,{height:a.height}));(function(){var d=$("<div/>").attr({id:"plura_form_upload_"+c}).appendTo(b),e=k.outerHeight(!0),
g={id:c,limit:a.limit,multiple:a.multiple,obj:a.obj,path:plura.utils.String.path(a.path,a.process||plura.constants.PHP),process:a.process||plura.constants.PHP,type:"upload"},f=k.outerWidth(!0);swfobject.embedSWF(plura.constants.SWF,d.attr("id"),f,e,a.swf.version,null,g,a.swf.params,null,q)})();return this};plura=plura||{};plura.fx=plura.fx||{};
plura.fx.Center=function(e){var b=$.isPlainObject(e.target)?e.target:e.target||$("body"),d=e.dimensions&&e.dimensions.height?e.dimensions.height:e.obj.height(),c=e.dimensions&&e.dimensions.width?e.dimensions.width:e.obj.width(),a=$.isPlainObject(b)?b.height||0:b.height(),f=$.isPlainObject(b)?b.left||0:b.position().left,k=$.isPlainObject(b)?b.top||0:b.position().top,b=$.isPlainObject(b)?b.width||0:b.width();e.obj.css({top:(a-d)/2+k,left:(b-c)/2+f,position:"absolute"})};plura=plura||{};
plura.fx=plura.fx||{};
plura.fx.Parallax=function(e){var b,d,c,a,f,k,g,h,m,l=function(){return{height:f.dimensions&&f.dimensions.height?f.dimensions.height:f.target.height(),width:f.dimensions&&f.dimensions.width?f.dimensions.width:f.target.width()}},q=function(){return g.x+d.x>g.x&&g.x+d.x<g.x+g.width&&g.y+d.y>g.y&&g.y+d.y<g.y+g.height?!0:!1};f=$.extend(!0,{},{enabled:{x:!0,y:!0},dimensions:null,rectangle:{width:0,height:0,y:0,x:0},restrict:{x:!0,y:!0},speed:8,target:null},e);b=f.enabled;g=f.rectangle;h=f.restrict;m=f.target;
c=m.position().left;a=m.position().top;d={x:0,y:0};k={x:0,y:0};$(document).mousemove(function(a){d={x:a.pageX-m.parent().offset().left-g.x,y:a.pageY-m.parent().offset().top-g.y}});setInterval(function(){if(g&&!(!g.width&&b.x||!g.height&&b.y)){var e,n;k.x=isNaN(k.x)?0:k.x;k.y=isNaN(k.y)?0:k.y;b.x&&(c=q()?d.x:c,g.width<l().width&&h.x||g.width>l().width&&!h.x?(e=-c*((l().width-g.width)/g.width)+g.x,k.x+=(e-m.position().left)/f.speed):b.x&&g.width>l().width&&h.x&&(e=((g.width-m.width)/2+c-m.position().left)/
f.speed,k.x+=e),1<Math.abs(e-m.position().left)&&m.css({left:k.x}));b.y&&(a=q()?d.y:a,g.height<l().height&&h.y||g.height>l().height&&!h.y?(n=-a*((l().height-g.height)/g.height)+g.y,k.y+=(n-m.position().top)/f.speed):b.x&&g.width>l().width&&h.x&&(n=((g.height-m.height)/2+a-m.position().top)/f.speed,k.y+=n),1<Math.abs(n-m.position().top)&&m.css({top:k.y}));m.trigger("PARALLAX",{dimensions:l(),inside:q(),mouse:d,rectangle:g,target:m,position:k})}},13);return this};plura=plura||{};
plura.fx=plura.fx||{};
plura.fx.Resize=function(e){var b,d=$.extend(!0,{},{increase:!0,height:null,inside:!1,target:null,width:null},e),c=d.obj,a=d.target,f,k;if(c){e=a?$.isPlainObject(a)&&a.height?a.height:$.isPlainObject(a)?c.height():a.height():$(window).height();b=a?$.isPlainObject(a)&&a.width?a.width:$.isPlainObject(a)?c.width():a.width():$(window).width();!a||$.isPlainObject(a)&&!a.x||$.isPlainObject(a)||a.position();!a||$.isPlainObject(a)&&!a.y||$.isPlainObject(a)||a.position();if(d.increase||!d.increase&&(c.height()>
e||c.width()>b))c.width()/c.height()>b/e&&d.inside||c.width()/c.height()<b/e&&!d.inside?(k=b/c.width()*c.width(),f=k*c.height()/c.width()):(f=e/c.height()*c.height(),k=f*c.width()/c.height());c.css({width:k,height:f});d.center&&plura.fx.Center({obj:c,target:d.target,dimensions:d.center.dimensions||!1})}};plura=plura||{};plura.layout=plura.layout||{};plura.layout.LoaderBar=function(e){var b;b=new plura.layout.ProgressBar(e);e.loader.core.on("LOADER_COMPLETE_ITEM",function(d,c){b.refresh(c.progress)})};
plura=plura||{};plura.layout=plura.layout||{};
plura.layout.Nav=function(e){var b,d,c,a,f=function(a,c){c&&(!c||b&&b[0]===a[0])||(c?a.addClass("active"):a.removeClass("active"));!c||b&&b[0]===a[0]||(b&&f(b,!1),b=a,d.trigger("SELECT",a.data()))},k=function(a){d.find(".i"+a).length?f(d.find(".i"+a),!0):c[a].data({active:!0})},g=function(a){f($(a.currentTarget),!0)},h=function(d){var b,e,f,h=$(d.target).data("index"),p;(a.width||a.height)&&plura.fx.Resize({target:{width:a.width,height:a.height},obj:$(d.target),inside:!0});f=$(d.target);a.wrap?(p=
f.parent(),p=a.wrap(f).data(f.data()).addClass("item i"+f.data("index")).click(g).appendTo(p)):p=f.addClass("item i"+f.data("index")).click(g);f.data("active")&&k(f.data("index"));f=p;p=f.prev();a.css&&(b=0!==h%a.limit&&0<h?p.width()+p.position().left+a.margin:0,e=0!==h%a.limit&&0<h?p.position().top:0===h%a.limit&&0<h?p.position().top+p.height()+a.margin:0,f.css({position:"absolute",left:b,top:e}));a.parallax&&(b=0<h&&p.position().left+p.width()>b+f.width()?p.position().left+p.width():b+f.width(),
e=0<h&&p.position().top+p.height()>e+f.height()?p.position().top+p.height():e+f.height(),f.parent().width(b).height(e));$(d.target).fadeIn();c[h+1]&&c[h+1].prop({src:a.path+a.data[h+1].thumb})};this.select=k;a=$.extend(!0,{},{css:{core:{position:"absolute",zIndex:2},parallax:{core:{position:"absolute",zIndex:1},holder:{position:"absolute",zIndex:2}}},height:null,limit:0,margin:5,overflow:!1,path:"",parallax:{},text:!1,width:null},e);d=$("<div/>").appendTo(a.target||"body").addClass(["nav",a.text?
"txt":"img"].join(" "));c=[];(function(b){var e,f;a.parallax&&(f=$("<div/>").prependTo(d).addClass("holder"),e=$.extend(!0,{rectangle:{x:0,y:0},target:f},a.parallax),$("<div/>").prependTo(d).addClass("parallax").css($.extend({},a.css.parallax.core,{width:e.rectangle.width,height:e.rectangle.height})),new plura.fx.Parallax(e),a.css&&(f.css(a.css.parallax.holder),a.overflow||d.css({overflow:"hidden",width:e.rectangle.width,height:e.rectangle.height})));for(e=0;e<b.length;e+=1)b[e].thumb&&!a.text?(c[e]=
$(new Image).appendTo(f||d).data({index:e}).hide().load(h),0===e&&c[e].prop({src:a.path+b[e].thumb})):$("<a/>").appendTo(f||d).addClass("item i"+e).data({index:e}).html(e+1).click(g)})(a.data);a.css&&d.css(a.css.core);this.core=d;return this};plura=plura||{};plura.layout=plura.layout||{};
plura.layout.ProgressBar=function(e){var b,d,c;this.refresh=function(a){d.height(b.height()).width(b.width()*a/100).show();100===a&&c.hide&&b.stop().fadeOut("slow")};this.reset=function(){d.fadeIn()};c=$.extend(!0,{},{bottom:!0,css:{core:{width:200,height:20,border:"2px solid #000"},bar:{backgroundColor:"#000"}},hide:!1,horizontal:!0,target:null},e);b=$("<div/>").appendTo(c.target||"body").addClass("plura progress").css(c.css.core);d=$("<div/>").appendTo(b).addClass("bar").css(c.css.bar).hide();(function(a){a.height(a.height()-
2*parseInt(a.css("border-top-width"),10)).width(a.width()-2*parseInt(a.css("border-top-width"),10))})(b);this.core=b;this.bar=d};plura=plura||{};plura.layout=plura.layout||{};
plura.layout.Refresh=function(e){var b,d,c=0,a,f,k=function(a){var c=d.format?d.format(a):a;d.fade?b.fadeOut(d.speed,function(){$(this).html(c).fadeIn(d.speed)}):b.html(c);b.trigger("CHANGE");d.refresh&&(clearInterval(f),f=setInterval(h,d.time))},g=function(a,b){var c,e=[],g;for(c in d.data)d.data.hasOwnProperty(c)&&(g=Math.floor(c/b),e[g]=e[g]||[],e[g].push(a[c]));return e},h=function(){"string"===typeof d.data?d.json?$.getJSON(d.data,null,function(a){k(a)}):$.get(d.data,null,function(a){k(a)}):
"object"===typeof d.data&&(k(a[c%a.length]),c+=1)};d=$.extend(!0,{},{data:!1,fade:!0,format:null,json:!1,limit:1,refresh:!0,speed:"slow",target:null,time:1E4},e);b=$("<div/>").appendTo(d.target||"body").addClass("refresh core");"object"===typeof d.data&&(a=g(d.data,d.limit));h()};plura=plura||{};plura.layout=plura.layout||{};
plura.layout.Slideshow=function(e){var b={auto:!0,cache:!1,center:!1,controls:!1,css:{core:{position:"relative"},media:{core:{position:"relative"},item:{position:"absolute"}}},data:null,height:null,id:"",navigation:{},outside:!1,path:"",resize:!1,target:null,timer:8E3,width:null,video:null},d,c,a,f=0,k,g,h,m,l,q,r,n=this,p=function(b){q&&clearTimeout(q);g&&g.core.remove();a=b;1<b.length&&(h.navigation&&(g=new plura.layout.Nav($.extend(!0,{},{data:b,path:h.path,target:c},h.navigation)),g.core.on("SELECT",
z)),h.swipe&&(l=new plura.event.Touch($.extend({target:k},"object"===typeof h.swipe?h.swipe:null)),l.core.on("TOUCHMOVE TOUCHSWIPE",A)));s(f,!0)},s=function(b,e){e&&(void 0!==d&&d.removeClass("active").addClass("inactive").fadeOut(function(){$(this).remove()}),f=b,d=w(a[f]).addClass("item active i"+f),c.trigger("CHANGE",{index:f}),g&&g.select(f),h.css&&d.css(h.css.media.item))},w=function(a){var b,d=a.data&&a.file,c=d?$("<div/>").addClass("mixed").appendTo(k):k,e;a.data&&(b=$("<div/>").html(a.data).appendTo(c).addClass("data").hide().fadeIn());
if(a.file)if(a.file.match(/\.(gif|jpg|png)$/i)||a.type&&a.type.match(/image/i))a=h.cache?h.path+a.file:h.path+a.file+"?"+(new Date).getTime(),b=$(new Image).load(x).appendTo(c).prop({src:a}).hide();else if(a.file.match(/\.(mp4)$/i)||a.type&&a.type.match(/video/i))e=new plura.media.Video($.extend({src:h.path+a.file,target:c},h.video)),b=e.core;return $(d?c:b).data({video:e||!1})},t=function(){s(f<a.length-1?f+1:0,!0)},v=function(){s(0<f?f-1:a.length-1,!0)},x=function(b){b=$(b.target).css({width:"auto",
height:"auto"}).fadeIn();var d=b.height(),c=h.resize&&h.resize.target?h.resize.target.height():h.height||k.height(),e=b.width(),g=h.resize&&h.resize.target?h.resize.target.width():h.width||k.width();h.resize&&(h.outside&&(e>c||d>c)||!h.outside)&&plura.fx.Resize({center:"boolean"===typeof h.resize||void 0===h.resize.center?!1:h.resize.center,inside:"boolean"===typeof h.resize||void 0===h.resize.inside?!0:h.resize.inside,obj:b,target:{width:g,height:c}});h.center&&plura.fx.Center({target:{width:g,height:c},
obj:b});h.auto&&1<a.length&&(clearTimeout(q),q=setTimeout(t,h.timer))},z=function(a,b){a.stopImmediatePropagation();b.index!==f&&s(b.index,!0)},A=function(a,b){a.stopPropagation();var c;switch(a.type){case "TOUCHMOVE":d.css({left:-b.delta.x});break;case "TOUCHSWIPE":c=b.direction&&b.direction.match(/(left|right)/)?("left"===b.direction?-1:1)*d.outerWidth():0,d.animate({left:c},"slow"),"left"===b.direction?t():"right"===b.direction&&v()}},u=function(){var a;for(a=0;a<r.items.length;a+=1)r.items[a].pause(!0,
!0)};this._index=function(a){if(void 0===a)return f;s(a,!0)};this._items=function(b){if(void 0===b)return a;p(b)};this.next=t;this.pause=function(a,b){clearTimeout(q);var c=void 0!==a?a:!m;c?c&&b&&d.data("video")&&d.data("video").pause(!0):q=setTimeout(t,h.timer);m=c};this.previous=v;(function(){h=$.extend({},b,e);c=$("<div/>").appendTo(h.target||"body").addClass("plura slideshow "+h.id);k=$("<div/>").appendTo(c).addClass("media");m=!1;"string"===typeof h.data?$.getJSON(h.data,function(a){p(a)}):
h.data&&"object"===typeof h.data&&p(h.data);h.css&&(c.css(h.css.core),k.css(h.css.media.core));n.core=c;r=plura.layout.Slideshow;r.items=r.items||[];r.stop=r.stop||u;r.items.push(n)})();return this};(function(){Object.defineProperties(plura.layout.Slideshow.prototype,{index:{get:function(){return this._index()},set:function(e){this._index(e)}},items:{get:function(){return this._items()},set:function(e){this._items(e)}}})})();plura=plura||{};plura.layout=plura.layout||{};
plura.layout.Social=function(e){var b,d=function(a){var d=$("<div/>").appendTo(b).addClass("fb-like"),c=[];a=$.extend(!0,{},a,{height:"button_count"===a.layout?21:"box_count"===a.layout?65:a.show_faces?80:35,href:a.href||window.location.href});for(var e in a)a.hasOwnProperty(e)&&c.push(e+"="+(a[e]||""));$("<iframe/>").appendTo(d).css({width:a.width,height:a.height,border:"none",overflow:"hidden"}).prop({allowTransparency:"true",frameborder:0,scrolling:"no",src:"//www.facebook.com/plugins/like.php?"+
c.join("&")})},c=function(a){var d=$("<div/>").appendTo(b).addClass("twitter"),c=$("<a/>").appendTo(d).prop({href:"http://twitter.com/share"}).addClass("twitter-share-button").html("Tweet"),e=document.createElement("script"),h;for(h in a)a.hasOwnProperty(h)&&("related"===h?a[h].user&&c.attr("data-"+h,a[h].user+(a[h].text?":"+a[h].text:"")):a[h]&&c.attr("data-"+h,a[h]));$(e).attr({type:"text/javascript",src:"http://platform.twitter.com/widgets.js"}).appendTo(d)};b=$("<div/>").addClass("share");e=$.extend(!0,
{},{like:{action:"like",colorsheme:"light",font:null,href:null,layout:"standard",show_faces:!0,width:450},twitter:{count:"horizontal",related:{text:null,via:null},text:null,via:null,url:null},target:null},e);e.target&&b.appendTo(e.target);e.like&&d(e.like);e.twitter&&c(e.twitter);return b};plura=plura||{};plura.layout=plura.layout||{};
plura.layout.Table=function(e){var b,d,c=function(d){a();var c,g,h=[],m={};for(c in d[0])d[0].hasOwnProperty(c);for(c=0;c<d.length;c+=1)for(g in d[c])d[c].hasOwnProperty(g)&&(h[c]=h[c]||[],m[g]=m[g]||{rowspan:1},e&&e.merge&&0<c&&d[c][g]===d[c-1][g]&&("string"===typeof e.merge?RegExp(e.merge).test(g):1)?(m[g].rowspan+=1,h[m[g].r][m[g].c].rowspan=m[g].rowspan):(m[g]={rowspan:1,r:c,c:h[c].length},h[c].push({value:d[c][g],span:m[g].rowspan})));var l,m=$("<table/>").appendTo(b);for(g=0;g<h.length;g+=1)for(c=
$("<tr/>").appendTo(m),d=0;d<h[g].length;d+=1)l=$("<td/>").appendTo(c).html(h[g][d].value||h[g][d]),h[g][d].rowspan&&1<h[g][d].rowspan&&l.prop({rowspan:h[g][d].rowspan})},a=function(){b.empty()};this.refresh=c;this.empty=a;d=$.extend(!0,{},{limit:0,merge:!0,target:null},e);this.core=b=$("<div/>").appendTo(d.target||"body").addClass("table core "+(d.classes||""));d.data&&c(d.data);return this};plura=plura||{};plura.media=plura.media||{};
plura.media.Audio=function(e){var b,d,c,a,f,k,g=function(d){console.log("B:"+a);a=void 0===d?!a:d;console.log("A:"+a);a?b.find(".play").removeClass("active").html(c.labels.play):b.find(".play").addClass("active").html(c.labels.pause);f?f.pause(a):a||f||r()},h=function(a){var c=$("<div/>").attr({id:"plura_media_audio_"+d}).appendTo(b);a={content:a,id:d,obj:"plura.media.Audio",type:"audio"};swfobject.embedSWF(plura.constants.SWF,c.attr("id"),"0","0","10.0.0",null,a,null,null,l)},m=function(b){g(!a)},
l=function(a){f=swfobject.getObjectById(a.id)},q=function(a){for(var b in k.instances)k.instances.hasOwnProperty(b)&&!b.match("i"+a)&&k.instances[b].pause(!0)},r=function(){c.data?h(c.data):c.path&&$.get(c.path,function(a){h(a)})};this.fade=function(a){b.find(".menu").fadeIn("slow")};this.pause=g;k=plura.media.Audio;k.count=void 0===k.count?0:k.count+1;k.instances=k.instances||{};k.instances["i"+k.count]=this;k.pause=k.pause||q;d=k.count;c=$.extend(!0,{},{auto:!0,data:null,controls:!0,css:{flash:{position:"relative",
height:0,width:0},test:{position:"absolute",zIndex:1E3,width:400,height:400}},fade:!0,labels:{pause:"Pause",play:"Play"},path:null,params:null,target:"body",test:!1},e);(function(){b=$("<div/>").appendTo(c.target).addClass("p audio").css({position:"relative"});var a=$("<ul/>").appendTo(b).addClass("menu controls");c.controls&&$("<li/>").appendTo(a).click(m).addClass("play");g(!c.auto)})();this.core=b};plura=plura||{};plura.media=plura.media||{};
plura.media.Video=function(e){var b,d,c=!0,a,f,k=this,g=function(b){a.empty();var c,d=b instanceof Array?b:[b],e;for(b=0;b<d.length;b+=1)c=d[b].src||d[b],e=d[b].type||"video/"+c.match(/\.([^.]+)$/)[1],$("<source/>").prop({src:c,type:e}).appendTo(a);return k},h=function(b){(c=void 0===b?!c:b)?(d.addClass("pause"),a[0].pause()):(d.removeClass("pause"),a[0].play())},m=function(b){void 0!==b&&(a[0].volume=b);return a[0].volume},l=function(a){a.stopImmediatePropagation();h()};this.pause=h;this.prop=function(b){a.prop(b);
return k};this.src=g;this.volume=m;b=new plura.net.Client;e=$.extend(!0,{},{autoplay:!0,controls:!0,pause:!0,preload:!0,loop:!0,wrap:!1},e);f={autoplay:e.autoplay,controls:e.controls,loop:e.loop,height:e.height,preload:e.preload,width:e.width,poster:e.poster};a=$("<video/>").prop(f);d=e.wrap?$("boolean"===typeof e.wrap?"<div/>":e.wrap).append(a).addClass("video"):a;d.appendTo(e.target||"body");e.src&&g(e.src);k.core=d;if(e.pause&&!e.controls||b.data.ios)a.on("click touchstart",l),e.wrap&&d.click(l);
e.volume&&m(e.volume);b.data.ios||h(!e.autoplay);return this};plura=plura||{};plura.net=plura.net||{};
plura.net.Client=function(e){var b;b=navigator.userAgent;var d=Boolean(b.match(/Android/i)),c=Boolean(b.match(/(explorer|MSIE)/i)),a=Boolean(b.match(/iPad/i)),f=Boolean(b.match(/iPhone/i)),k=Boolean(b.match(/iPod/i)),f=f?"iPhone":a?"iPad":k?"iPod":null,g=Boolean(null===document.location.href.match(/https?:\/\//)),h=Boolean(f||d||b.match(/Windows.+Touch/i)),m=parseInt(navigator.appVersion,10);c&&(m=parseInt(navigator.appVersion.match(/msie ([0-9\.]+)/i)[1],10));b={agent:b,android:d,ie:c,ios:f,ipad:a,
ipod:k,offline:g,touch:h,version:m};d=[];a=e&&e.ie?e.ie:11;if(b.ie){if(d.push("ie","ie"+b.version),b.version<a)for(d.push("ie_lte"+b.version),c=b.version;c<a;c+=1)d.push("ie_lt"+(c+1))}else b.ios?d=d.concat(["ios",b.ios.toLowerCase()]):b.android&&d.push("android");b.offline&&d.push("offline");d.push((b.touch?"":"no-")+"touch");b.classes=d;this.data=b;e&&e.classes&&$("body").addClass(b.classes.join(" "))};plura=plura||{};plura.net=plura.net||{};
plura.net.URLManager=function(e){var b={analytics:!0,lang:!0,separator:"#"},d,c,a,f,k,g,h=function(a,b,d,c,e){window._gaq&&(a=["_trackEvent",a,b,d,c],void 0!==e&&!0===e&&a.push(e),_gaq.push(a))},m=function(a){var b=[];a&&d&&b.push(d);k&&b.push(k);return b.join("/")},l=function(a){void 0!==a&&a!==k&&(k=a,c.push(k));window.location.href="#!/"+m(!0);f.analytics&&(a="/"+m(!0),window._gaq&&_gaq.push(["_trackPageview",a]))};this._history=function(){return c};this._index=function(){return a};this._lang=
function(a){void 0!==a&&(d=a,l());return d};this._path=function(a){void 0!==a&&l(a);return k};this._root=function(){return g};this._url=function(){return g+"#!/"+m(!0)+"/"};this.event=function(){h.apply(null,arguments)};this.perma=function(a){return a.match(g+".*?([^=]*[^/])/?$")[1]};(function(){var h=window.location.href;f=$.extend(!0,{},b,e);c=[];a=0;g=h.match(/[^#]+/)[0];h.match(/#!\/(.+)/)&&(h=h.match(/#!\/(.+)/)[1].replace(/\/$/,"").split(/\//),f.lang&&h[0].match(/^[a-z]{2}$/)&&(d=h.shift()),
k=h.join("/"),c.push(k))})()};(function(){Object.defineProperties(plura.net.URLManager.prototype,{history:{get:function(){return this._history()}},index:{get:function(){return this._index()}},lang:{get:function(){return this._lang()},set:function(e){this._lang(e)}},path:{get:function(){return this._path()},set:function(e){this._path(e)}},root:{get:function(){return this._root()}},url:{get:function(){return this._url()}}})})();plura=plura||{};plura.templates=plura.templates||{};
plura.templates.alert=plura.templates.alert||{};plura.templates.alert.Slide=function(e){var b,d;this.refresh=function(c,a){clearTimeout(d);b.html(a).stop(!0,!0).slideDown().addClass(c?"success":"error").removeClass(c?"error":"success");d=setTimeout(function(){b.slideUp()},2E3)};b=$("<p/>").appendTo(e.target||"body").addClass("alert").hide()};plura=plura||{};plura.templates=plura.templates||{};plura.templates.structures=plura.templates.structures||{};
plura.templates.structures.Content=function(e){var b,d,c,a=function(c,e){var m="string"===typeof c?k(c):c,l=void 0===e?!0:e;l&&(!l||b&&b[0]===m[0])||f(m,l);!l||b&&b[0]===m[0]||(b&&a(b,!1),b=m,d.trigger("REFRESH",m.data()))},f=function(a,b){!0===b?a.stop(!0).fadeIn().addClass("active"):a.stop(!0).fadeOut(function(){$(this).hide()}).removeClass("active")},k=function(a){a="object"===typeof a?a:{id:a};var b=[a.id,a.vanity||"",a.classes||""].join(" "),b=c[a.id]||$("<div/>").addClass("holder "+b).append(a.obj||
null).data(a).appendTo(d).hide();return c[a.id]=b};this.activate=a;this.disable=function(){b&&(a(b,!1),b=null)};this.get=k;e=$.extend(!0,{},{},e);d=$("<div/>").appendTo(e.target||"body").addClass(["content",e.classes||""].join(" "));c={};this.core=d;this.tree=c;return this};plura=plura||{};plura.templates=plura.templates||{};plura.templates.structures=plura.templates.structures||{};
plura.templates.structures.Menu=function(e){var b,d,c,a,f,k=this,g=function(c,e){var h=void 0===e?!0:e;if(!h||h&&(!b||b[0]!==c[0])){h?c.addClass("active"):c.removeClass("active");var k=c.data("id").replace(/i(.+)/,"$1").split("_").slice(0,-1),l,m;if(k.length)for(l=0;l<k.length;l+=1)if(m="i"+k.slice(0,l?-l:k.length).join("_"),h)0===l?f[m].addClass("parent"):f[m].addClass("ancestor");else if(!h)if(!b||0===l&&!b.data("id").match(m+"+_[0-9]+$"))f[m].removeClass("parent");else if(!b||0<l&&!b.data("id").match(m)||
1===l&&b.data("id").match(m+"+_[0-9]+$"))f[m].removeClass("ancestor");else break}!h||b&&b[0]===c[0]||(a=b,b=c,a&&g(a,!1),d.trigger("SELECT",c.data()))},h=function(a,b){var e,g,k=a.data("id").replace(/i(.+)/,"$1").split("_");if(void 0===b?!a.hasClass("open"):b)for(c.close&&d.find(".open").each(function(b){$(this).data("id").match(a.data("id"))||h($(this),!1)}),e=0;e<k.length;e+=1)g="i"+k.slice(0,e?-e:k.length).join("_"),f[g].addClass("open");else a.removeClass("open")},m=function(a){return c.leaf?
c.leaf(a):a.children?!1:!0},l=function(a){return c.trigger?c.trigger(a):$("<a/>").prop({href:"#"}).html(a.label).click(function(a){a.preventDefault()})},q=function(a,b,e){var k,p,n,r,u=function(a){h($(a.currentTarget).parent())},y=function(a){g($(this),!0)};for(n=0;n<a.length;n+=1)r=e?e+"_"+n:"i"+n,k={data:a[n],depth:r.split("_").length-1,id:r,label:a[n].label||a[n].name||a[n].vanity||a[n].id||("string"===typeof a[n]?a[n]:r),vanity:a[n].id||a[n].vanity||null},p=r+" node"+(k.vanity?" id-"+k.vanity:
"")+(a[n][c.nodeID]?" id-"+a[n][c.nodeID]:""),p=$(c.tags.leaf||c.tags).appendTo(b).data(k).addClass(p),k=l(k).appendTo(p).addClass("trigger"),f[r]=p,m(a[n])?(p.click(y).addClass("leaf"),d.trigger("COMPLETE_ITEM",p.data())):(k.click(u),q(a[n].children,$(c.tags.branch||c.tags).appendTo(p),r))},r=function(a){d.empty();f={};k.tree=f;c.data=a;q(c.data,d);c.first&&p(c.first);d.trigger("COMPLETE")},n=function(a){var c;if(void 0===a||"boolean"===typeof a){if(b)return b;for(c in f)if(f.hasOwnProperty(c)&&
m(f[c].data("data")))return f[c]}else{if("string"===typeof a)return f[a];if("number"===typeof a)return f["i"+a]}},p=function(a){a=n(a);g(a)};this.activate=g;this.disable=function(){b&&(a=b,b=null,g(a,!1))};this.get=n;this.refresh=r;this.select=p;c=$.extend(!0,{},{close:!0,data:null,first:!1,id:"",leaf:null,nodeID:"nodeID",tags:{branch:"<ul/>",leaf:"<li/>"}},e);d=$(c.tags.branch||c.tags).appendTo(c.target||"body").addClass("menu "+c.id);k.core=d;k.tree=f;c.data&&r(c.data)};plura=plura||{};
plura.templates=plura.templates||{};plura.templates.structures=plura.templates.structures||{};
plura.templates.structures.Tabs=function(e){var b,d,c,a,f=function(a){a=d.tree[a]?d.tree[a].data():"object"===typeof a?a:{id:a};return c.get({classes:k(a.id).join(" "),id:a.id,vanity:a.vanity})},k=function(a){var b=[],c=a.split("_").slice(0,-1);for(a=0;a<c.length;a+=1)b[a]=a?b.join("_")+"_"+c[a]:c[a].replace(/i/,"p");return b};this.disable=function(){d.disable();c.disable()};this.get=f;this.refresh=function(){d.refresh(a.tree)};this.select=function(a){d.select(a)};a=$.extend(!0,{},{first:!1,delay:!1,
id:null,menu:{},tree:null},e);b=$("<div/>").appendTo(a.target||"body").addClass("plura templates tabs core "+(a.id||""));d=new plura.templates.structures.Menu($.extend(!0,{},a.menu,{target:b,first:a.first}));d.core.on("COMPLETE COMPLETE_ITEM SELECT",function(a,d){a.stopPropagation();if("SELECT"===a.type){var e=f(d.id);c.activate(e)}b.trigger("MENU_"+a.type,d)});this.content=c=new plura.templates.structures.Content({target:b});this.core=b;this.menu=d;return this};plura=plura||{};
plura.utils=plura.utils||{};plura.utils.Cache=function(e){var b=(new Date).getTime();e+=e.match(/\?/)?e.match(/\&$/)?"":"&":"?";return e+b};plura=plura||{};plura.utils=plura.utils||{};plura.utils.Extend=function(e,b){function d(){}d.prototype=new e;b.prototype=new d;return b};plura=plura||{};plura.utils=plura.utils||{};
plura.utils.Flat=function(e,b,d){var c=[],a,f=b||{},k,g=plura.utils.Flat;for(a in e)if(e.hasOwnProperty(a))if(e[a]instanceof Array)for(b=0;b<e[a].length;b+=1)if("object"===typeof e[a][b]&&!(e[a][b]instanceof Array))c=c.concat(g(e[a][b],f,a));else{if("number"===typeof e[a][b]||"string"===typeof e[a][b])k=$.extend({},f),k[a]=e[a][b],c.push(k)}else"object"===typeof e[a]&&(f[d]=a,c=c.concat(g(e[a],f)));return c};plura=plura||{};plura.utils=plura.utils||{};
plura.utils.Hidden=function(e){var b=(new Date).getTime(),d=function(c){e.parents("body *").each(function(){$(this).is(":animated")||(!c&&void 0!==c||"none"!==$(this).css("display")?!1===c&&$(this).hasClass("i"+b)&&$(this).removeClass("i"+b).hide():$(this).addClass("i"+b).show())})};this.get=function(){d();var b={width:e.width(),height:e.height(),innerWidth:e.innerWidth(),innerHeight:e.innerHeight(),outerWidth:e.outerWidth(),outerHeight:e.outerHeight()};d(!1);return b};this.show=d};plura=plura||{};
plura.utils=plura.utils||{};
plura.utils.String={path:function(e,b){var d=[],c,a,f,k;c=function(a){a.match(/^https?:\/\//)||(a=window.location.href.replace(/[^\/]+$/,"")+a);return a};e=c(e);b=b?c(b):window.location.href;b.match(/^http/)&&(f=b.replace(/(https?:\/\/)(.+)(\/([^\/]+)?)$/g,"$1$2").split("/"));a=f.length;for(c=0;c<a;c+=1){if(e.match(f.join("/"))){k=e.replace(f.join("/"),"");break}f.splice(-1);d.push("..")}return d.join("/")+k},test:function(e,b){var d,c,a;d=e instanceof Array?e:[e];for(c=0;c<d.length;c+=1)if(a="string"===
typeof d[c]?RegExp(d[c].replace(/^(\/)(.*)(\/)$/,"$2")):d[c],!a.test(b))return!1;return!0}};