'use strict';const ModuleCompiler=function({data:n,prefix:l,process:c="ModuleCompiler.php"}){let b,g,f,m,e,k,h,p;const a=this,d=a=>{e.refresh(a.tree);h.refresh(a.result)},r=a=>{h.refresh(a.result);p.set("loading",!1)},q=a=>{a.stopImmediatePropagation();switch(a.type){case "COLLECTIONS":e.start(g.collection(a.detail));break;case "GROUPS":f=a.detail.id;k.refresh(g.type(f),g.returnTypes(f));g.load(f,d,k.get());break;case "FILES":case "PREFERENCES":p.set("loading",k.wait()),g.load(f,r,k.get(),e.get())}};
g=new ModuleDataManager({data:n,handler:d=>{b||(a.core=b=document.body.appendChild(document.createElement("div"))).classList.add("p-app-modulecompiler");m=new ModuleCompilerFilterCollection({data:d.filter(),prefix:"p-app-modulecompiler",target:b});m.core.addEventListener("COLLECTIONS",q);k=new ModuleCompilerPreferences({target:b,prefix:"p-app-modulecompiler"});k.core.addEventListener("PREFERENCES",q);e=new ModuleCompilerFileManager({prefix:"p-app-modulecompiler",target:b});["FILES","GROUPS"].forEach(a=>
e.core.addEventListener(a,q));h=new ModuleCompilerResultManager({prefix:"p-app-modulecompiler",target:b});p=new ModuleCompilerSystemStatus({app:a,prefix:"p-app-modulecompiler",target:b})},prefix:l,process:c})},ModuleCompilerFileManagerGroup=function({data:n,target:l}){var c,b,g,f,m;const e=(c,a=!0)=>{c?f.classList.add("on"):f.classList.remove("on");a&&h.activate(c);b=c},k=b=>{b?[c,m].forEach(a=>a.classList.add("on")):[c,m].forEach(a=>a.classList.remove("on"));g=b};(c=l.appendChild(document.createElement("div"))).classList.add(...["files-group",
"on"]);(l=c.appendChild(document.createElement("div"))).classList.add("controls");(f=l.appendChild(document.createElement("div"))).classList.add(...["controls-check"]);f.addEventListener("click",function(c){e(!b)});f.textContent=n.name||n.path;e(!0,!1);(m=l.appendChild(document.createElement("div"))).classList.add(...["controls-visibility"]);m.addEventListener("click",function(b){k(!g)});k(!0);l=void 0;var h=new ModuleCompilerFileManagerTree({data:n.core,target:c});h.core.addEventListener("CHANGE",
b=>{e(h.active(),!1)});this.core=c;this.active=h.active},ModuleCompilerFileManagerGroupNav=function({target:n}){let l,c,b,g,f,m;const e=d=>{let b=[],q;g=new Map;(f=document.createElement("div")).classList.add("index");d.forEach((a,d)=>{b.push({name:a.name,value:d});(q=f.appendChild(document.createElement("div"))).classList.add("i");g.set(q,d)});m=new ModuleCompilerForm({data:[{type:"select",values:b,change:a,blank:!1}],target:c});c.appendChild(f)},k=(a=0)=>{a!==l&&(1<b.length&&h(a),l=a,c.dispatchEvent(new CustomEvent("SELECT",
{detail:b[a]})))},h=a=>{m.core.querySelector("select").value=a;[...f.children].forEach((b,d)=>{a===d?(b.classList.add("active"),b.removeEventListener("click",p)):(b.classList.remove("active"),b.addEventListener("click",p))})},p=a=>{k(g.get(a.currentTarget))},a=({element:a})=>{k(Number(a.value))};(c=n.appendChild(document.createElement("div"))).classList.add("files-group-nav");this.core=c;this.refresh=a=>{for(;c.firstChild;)c.removeChild(c.firstChild);l=null;b=a;1<b.length&&e(b);k()}},ModuleCompilerFileManagerTree=
function({data:n,target:l}){let c,b,g,f,m;const e=function(a,d=!0){d&&!f.has(a)?(f.set(a,b.get(a).data),g.delete(a)):d||g.has(a)||(g.set(a,b.get(a).data),f.delete(a));b.get(a).parents&&b.get(a).parents.forEach(a=>{var c;if(!(c=d)&&(c=!d)){a:{c=b.get(a).children;let d;for(d=0;d<c.length;d+=1)if(f.has(c[d])){c=!0;break a}c=!1}c=!c}c&&k(a,d,!1)});h(a,d)},k=(a,d=!0,c=!0)=>{c&&b.get(a).children.forEach(a=>{b.get(a).children?k(a,d):e(a,d)});h(a,d)},h=function(a,d){d?b.get(a).node.classList.add("on"):b.get(a).node.classList.remove("on")},
p=function(a=!0){return a&&f.size||!a&&g.size?a?f:g:!1},a=function(){return{active:p(),inactive:p(!1),leaf:m.size,selected:f.size}},d=function(a,d){d=void 0!==d?d:b.get(a).children?!b.get(a).node.classList.contains("on"):!f.has(a);b.get(a).children?k(a,d):e(a,d)},r=function(a,c){var e,f=c?c+"_":"i",h,k;var g=document.createElement("ul");a.forEach((a,p)=>{e=f+p;(h=g.appendChild(document.createElement("li"))).classList.add(...["node",e]);(k=h.appendChild(q(a))).classList.add("trigger");b.set(e,{data:a,
node:h});b.set(h,e);a.children?(h.appendChild(r(a.children,e)).classList.add("branch"),k.addEventListener("click",t)):(h.addEventListener("click",u),h.classList.add("leaf"),m.set(h,a));c?(e.split("_").slice(0,-1).forEach((a,d,c)=>(b.get(e).parents=b.get(e).parents||[]).push(c.slice(0,d+1).join("_"))),(b.get(c).children=b.get(c).children||[]).push(e)):d(e)});return g},q=function(a){let d="string"===typeof a?a:a.name||a.vanity,b=document.createElement("span");b.textContent=d;a.path&&b.setAttribute("data-path",
a.path);return b},t=function(e){e=b.get(e.currentTarget.parentNode);d(e);c.dispatchEvent(new CustomEvent("CHANGE",{bubbles:!0,detail:a()}))},u=function(e){e=b.get(e.currentTarget);d(e);c.dispatchEvent(new CustomEvent("CHANGE",{bubbles:!0,detail:a()}))};this.activate=function(b=!0){n.forEach((a,c)=>d(`i${c}`,b));c.dispatchEvent(new CustomEvent("CHANGE",{bubbles:!0,detail:a()}))};this.active=p;b=new Map;g=new Map;f=new Map;m=new Map;(c=l.appendChild(r(n))).classList.add("tree");this.core=c},ModuleCompilerFileManager=
function({prefix:n,target:l}){let c,b,g,f;const m=function(b){b.stopImmediatePropagation();c.dispatchEvent(new CustomEvent("FILES"))};(c=l.appendChild(document.createElement("div"))).classList.add(`${n}-files`);g=new ModuleCompilerFileManagerGroupNav({target:c});g.core.addEventListener("SELECT",function(b){b.stopImmediatePropagation();c.dispatchEvent(new CustomEvent("GROUPS",{detail:b.detail}))});(f=c.appendChild(document.createElement("div"))).classList.add("inner");this.core=c;this.get=function(){let c=
[],f;b.forEach((b,e)=>{if(b.active()){if(f=b.active(!1),c[e]={},f){c[e].exclude=[];for(const a of f.values())c[e].exclude.push(a.path||a)}}else c[e]=!1});return c};this.refresh=c=>{for(b=[];f.firstChild;)f.removeChild(f.firstChild);c.forEach((c,e)=>{b[e]=new ModuleCompilerFileManagerGroup({data:c,target:f});b[e].core.addEventListener("CHANGE",m)})};this.start=b=>{g.refresh(b.groups);c.setAttribute("data-title",b.label)}},ModuleCompilerFilterCollection=function({data:n,prefix:l,target:c}){let b;(b=
c.appendChild(document.createElement("div"))).classList.add(`${l}-collections`);new ModuleCompilerForm({target:b,data:[{type:"select",values:n,change:({element:c})=>{b.dispatchEvent(new CustomEvent("COLLECTIONS",{detail:c.value}))}}]});this.core=b},ModuleCompilerFormLabelAlign={LEFT:"left",LEFT_WRAP:"left-wrap",RIGHT:"right",RIGHT_WRAP:"right-wrap"},ModuleCompilerForm=function({data:n,target:l}){let c,b;const g=this,f=(a,b)=>{a.forEach(a=>{let d;if(a instanceof Array||a.type.match(/(field)?set/))d=
b.appendChild(document.createElement(a.tag||"fieldset")),f(a.fields||a,d);else{switch(a.type){case "select":d=m({elementData:a.values,blank:a.blank});break;default:d=document.createElement("input")}d.classList.add("p-modulecompiler-form-element")}b.appendChild(d);void 0!==a.label&&e(a.label,d);k(d,a)})},m=({elementData:a,elementParent:d,elementParentID:c,blank:e=!0})=>{let f=d||document.createElement("select");!d&&e&&f.appendChild(document.createElement("option"));a.forEach((a,d)=>{let e=`${c?`${c}_`:
"i"}${d}`,h;a.values||a instanceof Array?(h=a.values&&(a.label||a.name)?a.label||a.name:`group${d}`,a=a.values||a,(d=f.appendChild(document.createElement("optgroup"))).setAttribute("label",h),m({elementData:a,elementParent:d,elementParentID:e})):(h=p([a.label,a.name,a.value,a]),(d=f.appendChild(document.createElement("option"))).value=p([a.value,h]),d.textContent=h,b.set(d,e))});return f},e=(a,d,b=ModuleCompilerFormLabelAlign.LEFT)=>{b=a.align||b;let c=document.createElement("label"),e=`p-modulecompiler-form-element-${Date.now()+
Math.floor(256*Math.random())}`;h(d,{id:e});h(c,{"for":e,"align-type":b});c.textContent=a.name||a;switch(b){case ModuleCompilerFormLabelAlign.LEFT:d.parentNode.insertBefore(c,d);break;case ModuleCompilerFormLabelAlign.LEFT_WRAP:d.parentNode.appendChild(c).appendChild(d);break;case ModuleCompilerFormLabelAlign.RIGHT:d.parentNode.insertBefore(c,d.nextSibling);break;case ModuleCompilerFormLabelAlign.RIGHT_WRAP:d.parentNode.appendChild(c).prepend(d)}c.classList.add(`align-${b}`);return c},k=(a,d)=>{let b=
{};if(!d.type||d.type.match(/((field)?set|checkbox|radio|text)/))if(!d.type.match(/(field)?set/)||d.tag)b.type=d.type||"text";void 0!==d.name&&(b.name=d.name);void 0!==d.change&&a.addEventListener("change",b=>d.change({data:d,form:c,element:a,obj:g}));void 0!==d.value&&(b.value=d.value);d.type.match(/(checkbox|radio)/)&&d.checked&&(b.checked=!0);h(a,b)},h=(a,b)=>Object.entries(b).forEach(([b,d])=>a.setAttribute(b,d)),p=a=>{let b;for(const d of a)if(b=d,void 0!==b)break;return b};n&&(b=new Map,g.core=
c=l.appendChild(document.createElement("form")),f(n,c))},ModuleCompilerPreferences=function({prefix:n,target:l}){let c,b;const g="ECMASCRIPT_2019 ECMASCRIPT_2018 ECMASCRIPT_2017 ECMASCRIPT_2016 ECMASCRIPT6 ECMASCRIPT5".split(" "),f=()=>{let b={returnType:e("[name=returnType]:checked").value};b.returnType.match(/join/)&&e("[name=minify]").checked&&(b={...b,minify:1,language:e("[name=language]").value,language_out:e("[name=language_out]").value});return b},m=({type:c,returnTypes:f}={})=>{f&&e("[name=returnType]",
!0).forEach(a=>{a.disabled=!f.includes(a.value)});e("[type=set]:not([name=main])",!0).forEach(a=>{e("[name=returnType]:checked").value===a.getAttribute("name")?a.classList.add("on"):a.classList.remove("on")});["language","language_out"].forEach(a=>{a=e(`[name="join"] [name=${a}]`);a.disabled=!e('[name="join"] [name=minify]').checked;if(c)a.classList[c.match(/js/)?"remove":"add"]("off")});b.core.querySelectorAll("[id]").forEach(a=>{let b=e(`label[for=${a.id}]`),f;b&&(f=[[a.disabled?"add":"remove",
"disabled"]],c&&f.push([a.classList.contains("off")?"add":"remove","off"]),f.forEach(a=>b.classList[a[0]](a[1])))})},e=(c,e=!1)=>b.core[e?"querySelectorAll":"querySelector"](c),k=b=>{m();b=f("minify").checked;c.dispatchEvent(new CustomEvent("PREFERENCES",{detail:{load:b}}))};(c=l.appendChild(document.createElement("div"))).classList.add(`${n}-preferences`);b=new ModuleCompilerForm({target:c,data:[{type:"set",name:"main",tag:"div",fields:[{name:"returnType",type:"radio",label:{name:"Link",align:"right"},
value:"link",checked:!0,change:k},{name:"returnType",type:"radio",label:{name:"Join",align:"right"},value:"join",change:k},{name:"returnType",type:"radio",label:{name:"Closure",align:"right"},value:"closure",change:k}]},{type:"set",name:"join",tag:"div",fields:[{name:"minify",type:"checkbox",label:{name:"Minify",align:ModuleCompilerFormLabelAlign.RIGHT_WRAP},change:k},{name:"language",type:"select",values:g,blank:!1,label:{name:"Language",align:ModuleCompilerFormLabelAlign.LEFT_WRAP},change:k},{name:"language_out",
type:"select",values:g,blank:!1,label:{name:"Language Out",align:ModuleCompilerFormLabelAlign.LEFT_WRAP},change:k}]}]});m();this.core=c;this.get=f;this.refresh=(b,c)=>m({type:b,returnTypes:c});this.wait=()=>f().minify},ModuleCompilerResultManager=function({prefix:n,target:l}){var c,b,g;const f={compiled_code:"Compiled Code",errors:"Errors",result:"Result",warnings:"Warnings",statistics:"Statistics"},m=(b,e=!0)=>{if(!e||e&&b!==c){e&&(c&&m(c,!1),c=b);{let c=g.get(b).nav.classList;b=g.get(b).content.classList;
e?(c.add("active"),b.add("on")):(c.remove("active"),b.remove("on"))}}},e=e=>{c=void 0;for(g=new Map;b.firstChild;)b.removeChild(b.firstChild);let h,k,a,d,l;(h=b.appendChild(document.createElement("ul"))).classList.add(`${n}-result-nav`);(d=b.appendChild(document.createElement("div"))).classList.add(`${n}-result-content`);Object.entries(e).forEach(([b,c])=>{(k=h.appendChild(document.createElement("li"))).classList.add(`${n}-result-nav-item`);(a=k.appendChild(document.createElement("a"))).textContent=
f[b]||b;a.setAttribute("href","#");a.addEventListener("click",a=>m(a.currentTarget));(l=d.appendChild(document.createElement("div"))).classList.add(`${n}-result-content-item`);l.appendChild(document.createElement("textarea")).textContent=c;g.set(a,{nav:k,content:l})})};(b=l.appendChild(document.createElement("div"))).classList.add(`${n}-result`);this.refresh=b=>{e("string"===typeof b?{result:b}:b);m(g.keys().next().value)}},ModuleCompilerSystemStatus=function({app:n,prefix:l,target:c}){var b;(b=c.appendChild(document.createElement("div"))).classList.add(`${l}-systemstatus`);
b.appendChild(document.createElement("div")).classList.add(`${l}-systemstatus-indicator`);this.set=(c,f=!0)=>{b.classList[f?"add":"remove"]("on");n.core.classList[f?"add":"remove"](`status-${c}`)}},ModuleDataManager=function({data:n,handler:l,prefix:c,process:b}){let g,f,m;const e=this,k=function(a,...b){let c=new FormData;b.forEach(a=>{for(let b in a)if(a.hasOwnProperty(b)){let d=a[b];"object"===typeof d&&(d=JSON.stringify(d));c.append(b,d)}});return new Request(a,{body:c,method:"POST"})},h=async function(a){"object"===
typeof a?m=p(a):"string"===typeof a&&(m=await fetch(a).then(a=>a.json()).then(a=>p(a)));l&&l(e)},p=(a,b)=>{let c=[];a.forEach((a,d)=>{let e=`${b?`${b}_`:"i"}${d}`;if(a.values||a instanceof Array)d=p(a.values||a,e),c.push({name:a.label,values:d});else{let b=[];d=a.data;let h=["join","link"];d instanceof Array&&(d[0]instanceof Array||d[0].group&&d[0].items)?d.forEach((c,d)=>{b.push({id:e+"_"+d,type:c.type||a.type||"js",name:c.group||"Group "+d,items:c instanceof Array?c:c.items instanceof Array?c.items:
[c.items]})}):b.push({id:e+"_0",type:a.type||"js",name:"Group 0",items:d instanceof Array?d:[d]});b.forEach(a=>{f.set(a.id,a);a.returnTypes=[].concat(h);for(let b=0;b<a.items.length;b+=1)if(a.items[b].closure){a.returnTypes.push("closure");break}});g.set(e,{groups:b,label:a.label});c.push({name:a.label,value:e})}});return c};g=new Map;f=new Map;e.load=function(a,d,e,g){let h=[];a=f.get(a);a.items.forEach((a,b)=>{g&&!g[b]||h.push({exclude:g&&g[b].exclude,filter:a.filter,join:a.join,name:a.name,path:(c||
"")+a.path,prefix:e.returnType.match(/link/)&&a[e.returnType]||"",top:a.top})});a=k(b,e,{data:h,type:a.type});fetch(a).then(a=>a.json()).then(a=>d(a))};e.filter=()=>m;e.collection=a=>g.get(a);e.returnTypes=a=>f.get(a).returnTypes;e.type=a=>f.get(a).type;n&&h(n)};
