'use strict';var ModuleCompiler=function(f){var {data:n,prefix:m,process:h="ModuleCompiler.php"}=f;let a,e,k,l,p,d;const r=b=>{k.refresh(b.tree);p.refresh(b.result)},g=b=>{p.refresh(b.result);d.set("loading",!1)},b=b=>{b.stopImmediatePropagation();switch(b.type){case "COLLECTIONS":k.start(a.collection(b.detail));break;case "GROUPS":e=b.detail.id;l.refresh(a.type(e),a.returnTypes(e));a.load(e,r,l.get());break;case "FILES":case "PREFERENCES":d.set("loading",l.wait()),a.load(e,g,l.get(),k.get())}};a=
new ModuleDataManager({data:n,prefix:m,process:h});(this.core=f=document.body.appendChild(document.createElement("div"))).classList.add("p-app-modulecompiler");(new ModuleCompilerFilterCollection({data:a.filter(),handler:a,prefix:"p-app-modulecompiler",target:f})).core.addEventListener("COLLECTIONS",b);l=new ModuleCompilerPreferences({target:f,prefix:"p-app-modulecompiler"});l.core.addEventListener("PREFERENCES",b);k=new ModuleCompilerFileManager({handler:a,prefix:"p-app-modulecompiler",target:f});
["FILES","GROUPS"].forEach(a=>k.core.addEventListener(a,b));p=new ModuleCompilerResultManager({prefix:"p-app-modulecompiler",target:f});d=new ModuleCompilerSystemStatus({app:this,prefix:"p-app-modulecompiler",target:f})},ModuleCompilerFileManagerGroup=function(f){var {data:n,target:m}=f,h,a,e;const k=function(d,e){e=void 0===e?!0:e;d?a.classList.add("on"):a.classList.remove("on");e&&p.activate(d)},l=function(a){a?[h,e].forEach(a=>a.classList.add("on")):[h,e].forEach(a=>a.classList.remove("on"))};
(h=m.appendChild(document.createElement("div"))).classList.add(...["files-group","on"]);(f=h.appendChild(document.createElement("div"))).classList.add("controls");(a=f.appendChild(document.createElement("div"))).classList.add(...["controls-check","on"]);a.addEventListener("click",function(d){k(!a.classList.contains("on"))});a.textContent=n.name||n.path;(e=f.appendChild(document.createElement("div"))).classList.add(...["controls-visibility","on"]);e.addEventListener("click",function(a){l(!e.classList.contains("on"))});
f=void 0;var p=new ModuleCompilerFileManagerTree({data:n.core,target:h});p.core.addEventListener("CHANGE",a=>{k(p.active(),!1)});this.core=h;this.inactive=()=>p.inactive()},ModuleCompilerFileManagerGroupNav=function(f){({target:f}=f);let n,m,h,a,e,k;const l=b=>{let c=[],d;a=new Map;(e=document.createElement("div")).classList.add("index");b.forEach((b,g)=>{c.push({name:b.name,value:g});(d=e.appendChild(document.createElement("div"))).classList.add("i");a.set(d,g)});k=new ModuleCompilerForm({data:[{type:"select",
values:c,change:g,blank:!1}],target:m});m.appendChild(e)},p=b=>{b=void 0===b?0:b;b!==n&&(1<h.length&&d(b),n=b,m.dispatchEvent(new CustomEvent("SELECT",{detail:h[b]})))},d=b=>{k.core.querySelector("select").value=b;[...e.children].forEach((a,d)=>{b===d?(a.classList.add("active"),a.removeEventListener("click",r)):(a.classList.remove("active"),a.addEventListener("click",r))})},r=b=>{p(a.get(b.currentTarget))},g=b=>{({element:b}=b);p(Number(b.value))};(m=f.appendChild(document.createElement("div"))).classList.add("files-group-nav");
this.core=m;this.refresh=function(b){for(;m.firstChild;)m.removeChild(m.firstChild);n=null;h=b;1<h.length&&l(h);p()}},ModuleCompilerFileManagerTree=function(f){var {data:n,target:m}=f;let h,a,e,k,l;const p=function(b,c){(c=void 0===c?!0:c)&&!k.has(b)?(k.set(b,a.get(b).data),e.delete(b)):c||e.has(b)||(e.set(b,a.get(b).data),k.delete(b));a.get(b).parents&&a.get(b).parents.forEach(b=>{var q;if(!(q=c)&&(q=!c)){a:{q=a.get(b).children;let c;for(c=0;c<q.length;c+=1)if(k.has(q[c])){q=!0;break a}q=!1}q=!q}q&&
d(b,c,!1)});r(b,c)},d=(b,c,e)=>{c=void 0===c?!0:c;(void 0===e||e)&&a.get(b).children.forEach(b=>{a.get(b).children?d(b,c):p(b,c)});r(b,c)},r=function(b,c){c?a.get(b).node.classList.add("on"):a.get(b).node.classList.remove("on")},g=function(b){return(b=void 0===b?!0:b)&&k.size||!b&&e.size?b?k:e:!1},b=function(){return{active:g(),inactive:g(!1),leaf:l.size,selected:k.size}},c=function(b,c){c=void 0!==c?c:a.get(b).children?!a.get(b).node.classList.contains("on"):!k.has(b);a.get(b).children?d(b,c):p(b,
c)},t=function(b,d){var e,q=d?d+"_":"i",g,f;var k=document.createElement("ul");b.forEach((b,h)=>{e=q+h;(g=k.appendChild(document.createElement("li"))).classList.add(...["node",e]);(f=g.appendChild(u(b))).classList.add("trigger");a.set(e,{data:b,node:g});a.set(g,e);b.children?(g.appendChild(t(b.children,e)).classList.add("branch"),f.addEventListener("click",v)):(g.addEventListener("click",w),g.classList.add("leaf"),l.set(g,b));d?(e.split("_").slice(0,-1).forEach((b,c,d)=>(a.get(e).parents=a.get(e).parents||
[]).push(d.slice(0,c+1).join("_"))),(a.get(d).children=a.get(d).children||[]).push(e)):c(e)});return k},u=function(b){let c="string"===typeof b?b:b.name||b.vanity,a=document.createElement("span");a.textContent=c;b.path&&a.setAttribute("data-path",b.path);return a},v=function(d){d=a.get(d.currentTarget.parentNode);c(d);h.dispatchEvent(new CustomEvent("CHANGE",{bubbles:!0,detail:b()}))},w=function(d){d=a.get(d.currentTarget);c(d);h.dispatchEvent(new CustomEvent("CHANGE",{bubbles:!0,detail:b()}))};this.activate=
function(a){a=void 0===a?!0:a;n.forEach((b,d)=>c(`i${d}`,a));h.dispatchEvent(new CustomEvent("CHANGE",{bubbles:!0,detail:b()}))};this.active=()=>g();this.inactive=()=>g(!1);a=new Map;e=new Map;k=new Map;l=new Map;(h=m.appendChild(t(n))).classList.add("tree");this.core=h},ModuleCompilerFileManager=function(f){var {handler:n,prefix:m,target:h}=f;let a,e,k,l;const p=function(d){d.stopImmediatePropagation();a.dispatchEvent(new CustomEvent("FILES"))};(a=h.appendChild(document.createElement("div"))).classList.add(`${m}-files`);
k=new ModuleCompilerFileManagerGroupNav({handler:n,target:a});k.core.addEventListener("SELECT",function(d){d.stopImmediatePropagation();a.dispatchEvent(new CustomEvent("GROUPS",{detail:d.detail}))});(l=a.appendChild(document.createElement("div"))).classList.add("inner");this.core=a;this.get=function(){let a=[],f;e.forEach((d,b)=>{if(f=d.inactive()){a[b]=[];for(const c of f.values())a[b].push(c.path||c)}else a[b]=!1});return a};this.refresh=a=>{for(e=[];l.firstChild;)l.removeChild(l.firstChild);a.forEach((a,
d)=>{e[d]=new ModuleCompilerFileManagerGroup({data:a,target:l});e[d].core.addEventListener("CHANGE",p)})};this.start=d=>{k.refresh(d.groups);a.setAttribute("data-title",d.label)}},ModuleCompilerFilterCollection=function(f){var {data:n,prefix:m,target:h}=f;let a;(a=h.appendChild(document.createElement("div"))).classList.add(`${m}-collections`);new ModuleCompilerForm({target:a,data:[{type:"select",values:n,change:e=>{({element:e}=e);a.dispatchEvent(new CustomEvent("COLLECTIONS",{detail:e.value}))}}]});
this.core=a};
function ModuleCompilerForm(f){var {data:n,target:m}=f;let h,a;const e=this,k=(a,b)=>{a.forEach(a=>{let c;if(a instanceof Array||a.type.match(/(field)?set/))c=b.appendChild(document.createElement(a.tag||"fieldset")),k(a.fields||a,c);else switch(a.type){case "select":c=l({elementData:a.values,blank:a.blank});break;default:c=document.createElement("input")}b.appendChild(c);if(void 0!==a.label){{var e=a.label,g=c,f=void 0;f=e.align||(void 0===f?"left":f);let b=document.createElement("label"),k=`p-modulecompiler-form-element-${Date.now()+
Math.floor(256*Math.random())}`;d(g,{id:k});d(b,{"for":k,"align-type":f});b.textContent=e.name||e;switch(f){case "left":g.parentNode.insertBefore(b,g);break;case "left_wrap":g.parentNode.appendChild(b).appendChild(g);break;case "right":g.parentNode.insertBefore(b,g.nextSibling);break;case "right_wrap":g.parentNode.appendChild(b).prepend(g)}}}p(c,a)})},l=d=>{var {elementData:b,elementParent:c,elementParentID:e,blank:g=!0}=d;let f=c||document.createElement("select");!c&&g&&f.appendChild(document.createElement("option"));
b.forEach((b,c)=>{let d=`${e?`${e}_`:"i"}${c}`,g;b.values||b instanceof Array?(g=b.values&&(b.label||b.name)?b.label||b.name:`group${c}`,b=b.values||b,(c=f.appendChild(document.createElement("optgroup"))).setAttribute("label",g),l({elementData:b,elementParent:c,elementParentID:d})):(g=r([b.label,b.name,b.value]),(c=f.appendChild(document.createElement("option"))).value=r([b.value,g]),c.textContent=g,a.set(c,d))});return f},p=(a,b)=>{let c={};if(!b.type||b.type.match(/((field)?set|checkbox|radio|text)/))if(!b.type.match(/(field)?set/)||
b.tag)c.type=b.type||"text";void 0!==b.name&&(c.name=b.name);void 0!==b.change&&a.addEventListener("change",c=>b.change({data:b,form:h,element:a,obj:e}));void 0!==b.value&&(c.value=b.value);b.type.match(/(checkbox|radio)/)&&b.checked&&(c.checked=!0);d(a,c)},d=(a,b)=>Object.entries(b).forEach(b=>{var [c,d]=b;return a.setAttribute(c,d)}),r=a=>{let b;for(const c of a)if(b=c,void 0!==b)break;return b};n&&(a=new Map,e.core=h=m.appendChild(document.createElement("form")),k(n,h))}
var ModuleCompilerPreferences=function(f){var {prefix:n,target:m}=f;let h,a;const e=()=>{let a={returnType:l("[name=returnType]:checked").value};a.returnType.match(/join/)&&(a=Object.assign({},a,{minify:l("[name=minify]").checked?1:0}));return a},k=e=>{var {type:d,returnTypes:f}=void 0===e?{}:e;f&&l("[name=returnType]",!0).forEach(a=>{a.disabled=!f.includes(a.value)});l("[type=set]:not([name=main])",!0).forEach(a=>{l("[name=returnType]:checked").value===a.getAttribute("name")?a.classList.add("on"):
a.classList.remove("on")});l('[name="join"] [name=es6]').disabled=!l('[name="join"] [name=minify]').checked;if(d)l('[name="join"] [name=es6]').classList[d.match(/js/)?"remove":"add"]("off");a.core.querySelectorAll("[id]").forEach(a=>{let b=l(`label[for=${a.id}]`),c;b&&(c=[[a.disabled?"add":"remove","disabled"]],d&&c.push([a.classList.contains("off")?"add":"remove","off"]),c.forEach(a=>b.classList[a[0]](a[1])))})},l=(e,d)=>a.core[(void 0===d?0:d)?"querySelectorAll":"querySelector"](e);f=a=>{k();a=
e("minify").checked;h.dispatchEvent(new CustomEvent("PREFERENCES",{detail:{load:a}}))};(h=m.appendChild(document.createElement("div"))).classList.add(`${n}-preferences`);a=new ModuleCompilerForm({target:h,data:[{type:"set",name:"main",tag:"div",fields:[{name:"returnType",type:"radio",label:{name:"Link",align:"right"},value:"link",checked:!0,change:f},{name:"returnType",type:"radio",label:{name:"Join",align:"right"},value:"join",change:f},{name:"returnType",type:"radio",label:{name:"Closure",align:"right"},
value:"closure",change:f}]},{type:"set",name:"join",tag:"div",fields:[{name:"minify",type:"checkbox",label:{name:"Minify",align:"right"},change:f},{name:"es6",type:"checkbox",label:{name:"ES6",align:"right"},checked:!0,change:f}]}]});k();this.core=h;this.get=e;this.refresh=(a,d)=>k({type:a,returnTypes:d});this.wait=()=>e().minify},ModuleCompilerResultManager=function(f){var {prefix:n,target:m}=f;let h;console.log(n);(f=m.appendChild(document.createElement("div"))).classList.add(`${n}-result`);h=f.appendChild(document.createElement("textarea"));
this.refresh=function(a){h.value=a}},ModuleCompilerSystemStatus=function(f){var {app:n,prefix:m,target:h}=f,a;(a=h.appendChild(document.createElement("div"))).classList.add(`${m}-systemstatus`);a.appendChild(document.createElement("div")).classList.add(`${m}-systemstatus-indicator`);this.set=(e,f)=>{f=void 0===f?!0:f;a.classList[f?"add":"remove"]("on");n.core.classList[f?"add":"remove"](`status-${e}`)}},ModuleDataManager=function(f){var {data:n,prefix:m,process:h}=f;let a,e,k;const l=(d,f)=>{let g=
[];d.forEach((b,c)=>{let d=`${f?`${f}_`:"i"}${c}`;if(b.values||b instanceof Array)c=l(b.values||b,d),g.push({name:b.label,values:c});else{let f=[];c=b.data;let h=["join","link"];c instanceof Array&&(c[0]instanceof Array||c[0].group&&c[0].items)?c.forEach((a,c)=>{f.push({id:d+"_"+c,type:a.type||b.type||"js",name:a.group||"Group "+c,items:a instanceof Array?a:a.items instanceof Array?a.items:[a.items]})}):f.push({id:d+"_0",type:b.type||"js",name:"Group 0",items:c instanceof Array?c:[c]});f.forEach(b=>
{e.set(b.id,b);b.returnTypes=[].concat(h);for(let a=0;a<b.items.length;a+=1)if(b.items[a].closure){b.returnTypes.push("closure");break}});a.set(d,{groups:f,label:b.label});g.push({name:b.label,value:d})}});return g},p=function(a,...e){let d=new FormData;e.forEach(b=>{for(let a in b)if(b.hasOwnProperty(a)){let c=b[a];"object"===typeof c&&(c=JSON.stringify(c));d.append(a,c)}});return new Request(a,{body:d,method:"POST"})};a=new Map;e=new Map;k=l(n);this.load=function(a,f,g,b){let c=[];a=e.get(a);a.items.forEach((a,
d)=>{c.push({exclude:b&&b[d],filter:a.filter,join:a.join,name:a.name,path:(m||"")+a.path,prefix:g.returnType.match(/link/)&&a[g.returnType]||"",top:a.top})});a=p(h,g,{data:c,type:a.type});fetch(a).then(a=>a.json()).then(a=>f(a))};this.filter=()=>k;this.collection=d=>a.get(d);this.group=a=>e.get(a);this.returnTypes=a=>e.get(a).returnTypes;this.type=a=>e.get(a).type};
