/**
 * Plura P Javascript Framework [http://plura.pt]
 * 
 * Copyright (c) 2015 Plura
 *
 * Date: 2015-07-20 12:00:00 (Mon, 20 Jul 2015)
 * Revision: 6246
 */
var plura={obj:function(e,c){var b,d=e.split("."),a=window;e.match(/^\./)&&(d=["plura"].concat(d.splice(1)));for(b=0;b<d.length;b+=1){if(void 0!==c)a[d[b]]=b<d.length-1?a[d[b]]||{}:c;else if(b<d.length-1&&void 0===a[d[b]])return;a=a[d[b]]}return a}};
plura.obj(".constants",{Paths:{PHP:$('script[src$="p.js"]').length?$('script[src$="p.js"]')[0].src.replace(/p\.js$/,"p.php"):null,SWF:$('script[src$="p.js"]').length?$('script[src$="p.js"]')[0].src.replace(/p\.js$/,"p.swf"):null},RegExp:{EMAIL:/^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/,EMPTY:/^\s*$/}});plura.obj(".events.EventDispatcher",function(){});
plura.events.EventDispatcher.prototype={constructor:plura.events.EventDispatcher,apply:function(e){e.addEventListener=plura.events.EventDispatcher.prototype.addEventListener;e.hasEventListener=plura.events.EventDispatcher.prototype.hasEventListener;e.removeEventListener=plura.events.EventDispatcher.prototype.removeEventListener;e.dispatchEvent=plura.events.EventDispatcher.prototype.dispatchEvent},addEventListener:function(e,c){void 0===this._listeners&&(this._listeners={});var b=this._listeners,d,
a=e.split(" ");for(d=0;d<a.length;d+=1)void 0===b[a[d]]&&(b[a[d]]=[]),-1===b[a[d]].indexOf(c)&&b[a[d]].push(c)},hasEventListener:function(e,c){if(void 0===this._listeners)return!1;var b=this._listeners;return void 0!==b[e]&&-1!==b[e].indexOf(c)?!0:!1},removeEventListener:function(e,c){if(void 0!==this._listeners){var b=this._listeners[e],d;void 0!==b&&(d=b.indexOf(c),-1!==d&&b.splice(d,1))}},dispatchEvent:function(e,c){if(void 0!==this._listeners){var b={type:e},d=this._listeners[e],a,f,g;if(void 0!==
d){b.target=this;a=[];f=d.length;for(g=0;g<f;g+=1)a[g]=d[g];for(g=0;g<f;g+=1)a[g].call(this,b,c)}}}};
plura.obj(".core.Loader",function(e){var c,b,d,a,f,g,h,l=function(a){"img"===a.dataType?b[a.name]=$(new Image).error(m).load(n).prop({src:a.path}):$.ajax({url:a.path,dataType:a.dataType,type:a.type,success:function(d){b[a.name]=d;k(b[a.name])},error:function(a,b,d){c.trigger("LOADER_ERROR",p())}})},k=function(b){a[d]=b;g=Math.ceil((d+1)/h.length*100);c.trigger("LOADER_COMPLETE_ITEM",p());d<h.length-1?(d+=1,r(d)):c.trigger("LOADER_COMPLETE",p())},m=function(a){c.trigger("LOADER_ERROR",p())},n=function(a){a=
$(a.target);k(a)},p=function(){return{content:b,index:d,items:a,item:$.extend({},h[d],{obj:b[h[d].name]}),progress:g}},r=function(a){l(h[a]);c.trigger("LOADER_CHANGE",p())},t=function(){h&&"img"===h[d].dataType&&b[h[d].name].off("load")},q=function(c){t();b={};a=[];d=0;var g=$.extend([],c);for(c=0;c<g.length;c+=1)g[c].dataType||(g[c].path.match(/\.(jpg|png|gif)$/i)?g[c].dataType="img":g[c].dataType="text"),g[c].label||(g[c].label=g[c].path.match(/([^\/?]+\.[^\/?]+)$/)[1]),g[c].type||(g[c].type="GET"),
f.cache||(g[c].path=plura.utils.Cache(g[c].path));h=g;r(d)};this._data=function(a){if(void 0===a)return b;q(a)};this._items=function(){return a};this.pause=t;f=$.extend(!0,{},{data:null,cache:!1,log:!1},e);this.core=c=f.target||$(window);f.data&&q(f.data);return this});(function(){Object.defineProperties(plura.core.Loader.prototype,{data:{get:function(){return this._data()},set:function(e){this._data(e)}},items:{get:function(){return this._items()}}})})();
plura.obj(".ecommerce.Cart",function(e){var c=this,b,d,a=function(a){var c,f={units:0,value:0},e;if("object"===typeof a)return{i:{units:a.units,value:a.value*a.units}};"string"===typeof a&&b?c=b[a]:d&&(c=d);if(c)for(e in c)c.hasOwnProperty(e)&&(f.units+=c[e].units,f.value+=c[e].total);return f},f=function(a){for(var b in a)if(a.hasOwnProperty(b))return!1;return!0};this.add=function(a){0<a.units?(d=d||{},d[a.id]?d[a.id].update(a):d[a.id]=new plura.ecommerce.CartItem(a),a.group&&(b=b||{},b[a.group]=
b[a.group]||{},b[a.group][a.id]=d[a.id])):(delete d[a.id],f(d)&&(d=null),b&&b[a.group]&&(delete b[a.group][a.id],f(b[a.group])&&(delete b[a.group],f(b)&&(b=null))));c.dispatchEvent("REFRESH",a)};this.getTotal=a;this._group=function(){return b};this._items=function(){return d};this._length=function(){var a,b=0;if(d)for(a in d)d.hasOwnProperty(a)&&(b+=1);return b};this._total=function(){return a()};$.extend({},!0,{currency:"\u20ac"},e)});
(function(){Object.defineProperties(plura.ecommerce.Cart.prototype,{group:{get:function(){return this._group()}},length:{get:function(){return this._length()}},items:{get:function(){return this._items()}},total:{get:function(){return this._total()}}});plura.events.EventDispatcher.prototype.apply(plura.ecommerce.Cart.prototype)})();
plura.obj(".ecommerce.CartItem",function(e){this.id=this.group=this.data=null;this.label="item";this.units=this.value=0;var c=this,b=function(b){for(var a in b)b.hasOwnProperty(a)&&a.match(/(data|group|id|label|value|units)/)&&(c[a]=b[a])};this.update=b;this._total=function(){return c.value*c.units};e&&b(e)});(function(){Object.defineProperties(plura.ecommerce.CartItem.prototype,{total:{get:function(){return this._total()}}})})();
plura.obj(".events.Touch",function(e){var c,b,d,a,f,g,h,l,k,m=function(){h=g=f=a=d=b=0;k=l=null};c=$.extend(!0,{},{length:72,target:null},e);this.core=c.target;m();c.target.on("MSPointerDown MSPointerMove MSPointerUp MSPointerOver MSPointerOut touchstart touchend touchmove touchcancel",function(e){e.stopImmediatePropagation();switch(e.type){case "MSPointerUp":case "touchend":e.preventDefault();if(1===b&&0!==f){h=Math.round(Math.sqrt(Math.pow(f-d,2)+Math.pow(g-a,2)));if(h>=c.length){e=d-f;var p=g-
a;Math.round(Math.sqrt(Math.pow(e,2)+Math.pow(p,2)));e=Math.atan2(p,e);l=Math.round(180*e/Math.PI);0>l&&(l=360-Math.abs(l));k=45>=l&&0<=l?"left":360>=l&&315<=l?"left":135<=l&&225>=l?"right":45<l&&135>l?"down":"up"}c.target.trigger("TOUCHSWIPE",{direction:h>=c.length?k:!1})}m();break;case "touchcancel":m();break;case "MSPointerMove":case "touchmove":e.preventDefault();e.originalEvent.touches&&1!==e.originalEvent.touches.length?m():(f=e.originalEvent.pageX||e.originalEvent.touches[0].pageX,g=e.originalEvent.pageY||
e.originalEvent.touches[0].pageY,c.target.trigger("TOUCHMOVE",{delta:{x:d-f,y:a-g},position:{x:f,y:g}}));break;case "MSPointerDown":case "touchstart":e.preventDefault(),b=e.originalEvent.touches?e.originalEvent.touches.length:1,1===b?(d=e.originalEvent.pageX||e.originalEvent.touches[0].pageX,a=e.originalEvent.pageY||e.originalEvent.touches[0].pageY):m()}})});
plura.obj(".form.elements.FormLabel",function(e){var c=e.field,b=e.target,d=e.data.name,a=e.data.label,f=e.data.type;e=a&&a.align?a.align:f&&f.match(/(checkbox|radio)/)?plura.form.FormLabelAlignType.RIGHT:plura.form.FormLabelAlignType.LEFT;a=a&&(a.text||(typeof a).match(/(string|number)/))?a.text||a:d;d=$("<label/>").text(a).prop({"for":d}).addClass("type-"+(f||"text"));switch(e){case plura.form.FormLabelAlignType.LEFT:d.insertBefore(c);break;case plura.form.FormLabelAlignType.LEFT_WRAP:d.append(c).appendTo(b);
break;case plura.form.FormLabelAlignType.RIGHT:d.insertAfter(c);break;case plura.form.FormLabelAlignType.RIGHT_WRAP:d.prepend(c).appendTo(b)}return d});
plura.obj(".form.elements.FormSelect",function(e){var c,b=function(c,a){var f,g,h;for(f=0;f<a.length;f+=1)if(a[f].values||a[f]instanceof Array)g=a[f].values&&a[f].label?a[f].label:"group"+f,h=a[f].values||a[f],g=$("<optgroup/>").prop({label:g}).appendTo(c),b(g,h);else{h=c;g=a[f];var l=void 0,k=l=void 0;"string"===typeof g?l=k=g:(k=void 0!==g.value?g.value:g[e.name],l=g.label||g.name||g.value);l=$("<option/>").prop({value:k}).appendTo(h).html(l);g.data&&l.data(g.data)}};this.prop=function(b){c.prop(b)};
this.data=function(d){c.empty();"select"===e.type&&c.append("<option/>");b(c,d)};this.val=function(b){c.val(b)};this.core=c=$("<select/>")});
plura.obj(".form.Form",function(e){var c,b,d,a,f,g=function(a){var b=d[a.name].field;a.values&&a.type&&a.type.match(/(list|select)/)&&b.data(a.values);a.value&&b.val(a.value)},h=function(b,e){var m,n,p=b||(a.submit?a.fields.concat([{type:"submit",value:a.submit}]):a.fields);for(m=0;m<p.length;m+=1)if(p[m]instanceof Array||p[m].fields||p[m].type&&p[m].type.match(/^(field)?set$/i))n=$("<fieldset/>").appendTo(e||c).prop({name:p[m].name}),p[m]instanceof Array||$("<legend/>").appendTo(n).text(p[m].label||
p[m].name),h(p[m].fields||p[m],n);else{n=p[m];var r=e||c,t=void 0,q=void 0,v=void 0;$("<div/>");var w=void 0,u=void 0;switch(n.type){case "list":case "select":q=new plura.form.elements.FormSelect(n);t=q.core;break;case "textarea":t=$("<textarea/>");n.wysiwyg&&window.tinyMCE&&(w=tinymce.DOM.uniqueId(),u=$.extend(!0,a.tinyMCE,{editor_selector:w},"number"!==typeof n.wysiwyg?n.wysiwyg:null,{width:300}),t.addClass(w+" tinyMCE").prop({id:w}).appendTo("body").width(t.width()).height(t.height()),tinyMCE.init(u));
break;case "file":q=new plura.form.Upload($.extend({name:n.name,target:r},a.upload));t=q.core;f.push(q);break;default:t=$("<input/>"),jQuery.ui&&"date"===n.type&&t.datepicker({dateFormat:"yy-mm-dd"})}var w=t,u=n,y=u.name,x={},z=$.extend;u.disabled&&z(x,{disabled:u.disabled});(a.id||u.id)&&z(x,{id:!0===u.id?u.name:u.id});u.type&&u.type.match(/(list|select|textarea)/)||z(x,{type:u.type&&"date"!==u.type?u.type:"text"});u.type&&u.type.match(/list/)&&z(x,{multiple:!0,size:u.size||1});u.value&&u.type.match(/(checkbox|radio)/)&&
z(x,{value:u.value});u.type&&u.type.match(/list/)&&(y+="[]");z(x,{name:y});(w.core||w).prop(x);n.change&&t.change(n.change);n.type&&n.type.match(/file/)||t.appendTo(r);n.label&&(v=new plura.form.elements.FormLabel({data:n,field:t,target:r}));d[n.name]={data:n,field:q||t,label:v};void 0===n.value&&!n.values||n.type&&!n.type.match(/(list|select|submit|text|textarea)/)?n.type&&n.type.match(/(checkbox|radio)/)&&n.checked&&t.prop("checked",!0):g(n)}};this._query=function(){return b._query()};this._params=
function(a){return b._params(a)};this.populate=function(a){var b,c,e;for(b in a)if(a.hasOwnProperty(b)&&d[b])switch(c=d[b].field,e=d[b].data,e.type){case "checkbox":c.prop("checked","0"!==a[b]);break;default:e.type&&e.type.match(/textarea/i)&&e.wysiwyg?tinyMCE.get(c.prop("id")).setContent(a[b]||""):e.type&&e.type.match(/file/)||c.val(a[b])}};this.refresh=function(a){var b,c;for(c in a)a.hasOwnProperty(c)&&d[c]&&(b=$.extend(!0,{},d[c].data,{values:a[c]}),g(b))};this.reset=function(a){b.reset(a)};a=
$.extend(!0,{},{alert:{success:"Success! Content updated!",error:"Error! Content not updated! :("},check:null,fields:null,id:!1,path:null,params:null,reset:!1,send:!0,submit:"Submit",tinyMCE:{mode:"specific_textareas",theme:"advanced",plugins:"fullscreen",theme_advanced_buttons1:"bold,italic,underline,|,strikethrough,justifyleft,justifycenter,justifyright,justifyfull,|,bullist,numlist,outdent,indent",theme_advanced_buttons2:"formatselect,sub,sup,code,fullscreen,link,unlink,|,forecolor,removeformat"}},
e);c=$("<form/>").appendTo(a.target);f=[];d={};this.core=c;this.objects=d;this.uploads=f;h();b=new plura.form.FormManager($.extend(!0,{},{ajax:a.ajax||{},alert:a.alert||{},check:a.check||{},params:a.params||{}},{path:a.path,reset:a.reset,send:a.send,target:this,type:"getJSON"}));return this});(function(){Object.defineProperties(plura.form.Form.prototype,{query:{get:function(){return this._query()}},params:{get:function(){return this._params()},set:function(e){this._params(e)}}})})();
plura.obj(".form.FormLabelAlignType",{LEFT:"left",LEFT_WRAP:"left_wrap",RIGHT:"right",RIGHT_WRAP:"right_wrap"});
plura.obj(".form.FormManager",function(e){var c,b,d,a=function(a){c.find("input[type=file]").each(function(b){d[b]=new plura.form.Upload($.extend({name:$(this).attr("name"),target:c},a));d[b].core.replaceAll($(this))})},f=function(a){var b=$.extend({},{not:":button, :submit, :reset",checked:!0,selected:!0,upload:!0}),e=c.find(":input").not(b.not);e.not(":checkbox, :radio").val("");b.checked&&e.prop("checked",!1);b.selected&&e.prop("selected",!1);for(b=0;b<d.length;b+=1)d[b].reset(a);window.tinyMCE&&
c.find(".tinyMCE").each(function(){tinymce.get($(this).prop("id")).setContent("");tinymce.get($(this).prop("id")).nodeChanged()})},g=function(){var a=b.path||window.location.href,d=function(a,b){return"string"===typeof a?a:a.alert?a:$.extend(!0,{},a,{alert:b})};console&&console.log(b.ajax.dataType+" | "+b.ajax.type+" | "+a+":"+h());$.ajax({url:a,data:h(),dataType:b.ajax.dataType,type:b.ajax.type,success:function(a){c.trigger("FORM_REQUEST_SUCCESS",d(a,b.alert.complete));!a.success||"true"!==a.success&&
1!==a.success?(a.success&&"false"===a.success||0===a.success)&&c.trigger("FORM_PROCESS_ERROR",d(a,b.alert.error)):(b.reset&&f(!0),c.trigger("FORM_PROCESS_SUCCESS",d(a,b.alert.success)))},error:function(a,b,c){}});c.trigger("FORM_SUBMIT",{alert:b.alert.submit})},h=function(){return c.serialize()+"&"+$.param(b.params||{})};this._query=h;this._params=function(a){void 0!==a&&(b.params=$.extend(!0,b.params||{},a));return b.params};this.reset=f;b=$.extend(!0,{},{ajax:{dataType:"json",type:"GET"},alert:{complete:"Your form was submited.",
error:"There was an error processing your form.",field:"Please correctly fill the % field. Thank you",submit:"Form is being submitted. Please wait.",success:"Your form was successfully processed! Thank you."},check:!1,params:null,path:null,replace:!0,reset:!1,send:!0,target:null,upload:{}},e);c=b.target.core||b.target;d=b.target.uploads||[];this.form=c;b.replace&&a(b.upload);c.submit(function(a){a.preventDefault();window.tinyMCE&&tinyMCE.triggerSave();if(!(a=!b.check))a:{var d,e,h,f;for(d=0;d<b.check.length;d+=
1)for(a=b.check[d],h=a.rules?a.rules instanceof Array?a.rules:[a.rules]:[{alert:a.alert||null}],e=0;e<h.length;e+=1)if(f=plura.utils.String.test([/\./,/#/],a.id)?c.find(a.id):c.find("*[name="+a.id+"]"),h[e].exp&&!plura.utils.String.test(h[e].exp,f.val())||!h[e].exp&&f.val().match(/^\s*$/)){a=h[e].alert||b.alert.field.replace(/%/,a.id);c.trigger("FORM_VALIDATION_ERROR",{alert:a});a=!1;break a}c.trigger("FORM_VALIDATION_SUCCESS");a=!0}a&&b.send&&g()}).find("input[type=reset]").click(function(a){a.preventDefault();
f()})});(function(){Object.defineProperties(plura.form.FormManager.prototype,{query:{get:function(){return this._query()}},params:{get:function(){return this._params()},set:function(e){this._params(e)}}})})();
plura.obj(".form.upload.File",function(e){var c,b,d,a,f,g,h=function(){b.slideUp("slow",m);g.reset()},l=function(a){$.getJSON(f.process,{action:"delete",file:d.file,path:f.path,type:"upload"},function(c){"true"===c.success&&a&&(h(),b.trigger("FORM_UPLOAD_REMOVE"))})},k=function(a){if(d&&!a)l(!0);else if(!d||d&&a)d||(swf.cancel(f.id),b.trigger("FORM_UPLOAD_CANCEL")),h()},m=function(){$(this).remove()};this.update=function(h){d=h;a=a||$("<input/>").prop({type:"hidden",name:e.name+"[]"}).appendTo(b);
a.val(h.file+"|"+h.name);c.val(f.label.remove);console.log(d)};this.clean=function(){d&&l();c.val(f.label.cancel)};this.reset=k;this.refresh=function(a){g.refresh(a)};f=$.extend(!0,{},{css:{button:{border:"none","float":"right","text-align":"center",width:50},file:{"float":"left",width:"100%"},progress:{"float":"left"}},height:20,label:{cancel:"Cancel",remove:"Delete"},margin:5,swf:null,width:100},e);b=$("<div/>").addClass("file i"+f.id).appendTo(f.target);g=new plura.layout.ProgressBar({target:b,
css:{core:$.extend({},f.css.file,{width:f.width-3*f.margin-f.css.button.width})}});c=$("<input/>").prop({type:"button"}).val(f.label.cancel).addClass("delete").appendTo(b).click(function(a){k()});this.core=b;b.css($.extend({},f.css.file,{"margin-bottom":f.margin}));c.css($.extend({},f.css.button,{height:f.height}));return this});
plura.obj(".form.Upload",function(e){var c,b,d,a,f,g,h,l=function(){c.children(".files").slideUp("slow",function(){$(this).remove()})},k=function(a){if(b){for(var c in b)b.hasOwnProperty(c)&&(b[c].reset(a),delete b[c]);b=null}l()},m=function(a){a.stopImmediatePropagation();1===c.children(".files").children().length&&k()},n=function(a){var b=$("<div/>");f=swfobject.getObjectById(a.id);b.replaceAll(c);$("body").prepend(c);$("#"+a.id).css({left:g.position().left,position:"absolute",top:g.position().top,
zIndex:100});c.replaceAll(b)},p=function(a,b,c){"true"===c.success&&h.instances["i"+a].update(b,c)},r=function(a,b){h.instances["i"+a].init(b)},t=function(a,b,c){h.instances["i"+a].refresh(b,c)},q=function(a){};this.init=function(d){a.multiple||!a.multiple&&!b?(b=b||{},b["i"+d]=new plura.form.upload.File($.extend(!0,{},a.file,{id:d,name:a.name,path:plura.utils.String.path(a.path,a.process||plura.constants.Paths.PHP),process:a.process||plura.constants.Paths.PHP,swf:f,target:c.children(".files").length?
c.children(".files"):$("<div/>").appendTo(c).addClass("files").css($.extend({},a.css.files,{"margin-top":a.margin,padding:a.margin+"px "+a.margin+"px 0 "+a.margin+"px",width:a.width-2*a.margin})),width:a.width})),b["i"+d].core.on("FORM_UPLOAD_CANCEL FORM_UPLOAD_REMOVE",m)):!a.multiple&&b&&b["i"+d].clean()};this.refresh=function(a,c){b["i"+a].refresh(c)};this.reset=k;this.update=function(a,c){b["i"+a].update(c)};h=plura.form.Upload;h.count=void 0===h.count?0:h.count+1;h.instances=h.instances||{};h.instances["i"+
h.count]=this;h.complete=h.complete||p;h.init=h.init||r;h.refresh=h.refresh||t;h.test=h.test||q;d=h.count;a=$.extend(!0,{},{css:{files:{"float":"left","background-color":"#e0e0e0"},progress:{"float":"left"},trigger:{border:"none","float":"right","text-align":"center",width:70}},file:{},label:{cancel:"Cancel",remove:"Delete",upload:"Upload"},height:30,limit:0,margin:5,multiple:!1,path:"",obj:"plura.form.Upload",swf:{params:{allowscriptaccess:"always",menu:"false",wmode:"transparent"},version:"10.0"},
process:null,width:220},e);c=$("<div/>").css({position:"relative"}).addClass("upload i"+d).appendTo(a.target);new plura.layout.ProgressBar({target:c,css:{core:$.extend({},a.css.progress,{width:a.width-a.css.trigger.width-a.margin,height:a.height})}});g=$("<input/>").prop({type:"button",value:a.label.upload}).addClass("trigger").appendTo(c);this.core=c;c.css({width:a.width});g.css($.extend({},a.css.trigger,{height:a.height}));(function(){var b=$("<div/>").attr({id:"plura_form_upload_"+d}).appendTo(c),
e=g.outerHeight(!0),h={id:d,limit:a.limit,multiple:a.multiple,obj:a.obj,path:plura.utils.String.path(a.path,a.process||plura.constants.Paths.PHP),process:a.process||plura.constants.Paths.PHP,type:"upload"},f=g.outerWidth(!0);swfobject.embedSWF(plura.constants.Paths.SWF,b.attr("id"),f,e,a.swf.version,null,h,a.swf.params,null,n)})();return this});
plura.obj(".fx.Center",function(e){var c=$.isPlainObject(e.target)?e.target:e.target||$("body"),b=e.dimensions&&e.dimensions.height?e.dimensions.height:e.obj.height(),d=e.dimensions&&e.dimensions.width?e.dimensions.width:e.obj.width(),a=$.isPlainObject(c)?c.height||0:c.height(),f=$.isPlainObject(c)?c.left||0:c.position().left,g=$.isPlainObject(c)?c.top||0:c.position().top,c=$.isPlainObject(c)?c.width||0:c.width();e.obj.css({top:(a-b)/2+g,left:(c-d)/2+f,position:"absolute"})});
plura.obj(".fx.Parallax",function(e){var c,b,d,a,f,g,h,l,k,m=function(){return{height:f.dimensions&&f.dimensions.height?f.dimensions.height:f.target.height(),width:f.dimensions&&f.dimensions.width?f.dimensions.width:f.target.width()}},n=function(){return h.x+b.x>h.x&&h.x+b.x<h.x+h.width&&h.y+b.y>h.y&&h.y+b.y<h.y+h.height?!0:!1};f=$.extend(!0,{},{enabled:{x:!0,y:!0},dimensions:null,rectangle:{width:0,height:0,y:0,x:0},restrict:{x:!0,y:!0},speed:8,target:null},e);c=f.enabled;h=f.rectangle;l=f.restrict;
k=f.target;d=k.position().left;a=k.position().top;b={x:0,y:0};g={x:0,y:0};$(document).mousemove(function(a){b={x:a.pageX-k.parent().offset().left-h.x,y:a.pageY-k.parent().offset().top-h.y}});setInterval(function(){if(!(!h||!h.width&&c.x||!h.height&&c.y)){var e,r;g.x=isNaN(g.x)?0:g.x;g.y=isNaN(g.y)?0:g.y;c.x&&(d=n()?b.x:d,h.width<m().width&&l.x||h.width>m().width&&!l.x?(e=-d*((m().width-h.width)/h.width)+h.x,g.x+=(e-k.position().left)/f.speed):c.x&&h.width>m().width&&l.x&&(e=((h.width-k.width)/2+d-
k.position().left)/f.speed,g.x+=e),1<Math.abs(e-k.position().left)&&k.css({left:g.x}));c.y&&(a=n()?b.y:a,h.height<m().height&&l.y||h.height>m().height&&!l.y?(r=-a*((m().height-h.height)/h.height)+h.y,g.y+=(r-k.position().top)/f.speed):c.x&&h.width>m().width&&l.x&&(r=((h.height-k.height)/2+a-k.position().top)/f.speed,g.y+=r),1<Math.abs(r-k.position().top)&&k.css({top:g.y}));k.trigger("PARALLAX",{dimensions:m(),inside:n(),mouse:b,rectangle:h,target:k,position:g})}},13);return this});
plura.obj(".fx.Resize",function(e){var c,b,d={increase:!0,height:null,inside:!1,target:null,width:null},a,f,g=function(){var d=f.target;c=d?$.isPlainObject(d)&&d.height?d.height:$.isPlainObject(d)?a.height():d.height():f.height||$(window).height();b=d?$.isPlainObject(d)&&d.width?d.width:$.isPlainObject(d)?a.width():d.width():f.width||$(window).width();!d||$.isPlainObject(d)&&!d.x||$.isPlainObject(d)||d.position();!d||$.isPlainObject(d)&&!d.y||$.isPlainObject(d)||d.position()},h=function(){var d,e;
if(f.increase||!f.increase&&(a.height()>c||a.width()>b))a.width()/a.height()>b/c&&f.inside||a.width()/a.height()<b/c&&!f.inside?(d=b/a.width()*a.width(),e=d*a.height()/a.width()):(e=c/a.height()*a.height(),d=e*a.width()/a.height());a.css({width:d,height:e});f.center&&plura.fx.Center({obj:f.obj,target:f.target,dimensions:f.center.dimensions||!1})};e.obj&&(f=$.extend(!0,{},d,e),a=f.obj,g(),h())});
plura.obj(".layout.LoaderBar",function(e){var c;c=new plura.layout.ProgressBar(e);e.loader.core.on("LOADER_COMPLETE_ITEM",function(b,d){c.refresh(d.progress)})});
plura.obj(".layout.navigation.Nav",function(e){var c,b,d,a,f,g=function(a,d){d&&(!d||c&&c[0]===a[0])||(d?a.addClass("active"):a.removeClass("active"));!d||c&&c[0]===a[0]||(c&&g(c,!1),c=a,b.trigger("SELECT",a.data()))},h=function(c){b.find(".i"+c).length?g(b.find(".i"+c),!0):a[c].data({active:!0})},l=function(b){a[b].prop({src:f.path+(f.data[b].thumb||f.data[b].file)})},k=function(a){g($(a.currentTarget),!0)},m=function(c){var e,g,m,q;c=$(c.target);var v=c.data("index");m=f.wrap?f.wrap(c).data(c.data()):
c;c.data("active")&&h(c.data("index"));m=m.addClass("item i"+c.data("index")).click(k).appendTo(d||b);q=m.prev();(f.width||f.height)&&plura.fx.Resize({target:{width:f.width,height:f.height},obj:c,inside:!0});f.css&&(e=0!==v%f.limit&&0<v?q.width()+q.position().left+f.margin:0,g=0!==v%f.limit&&0<v?q.position().top:0===v%f.limit&&0<v?q.position().top+q.height()+f.margin:0,m.css({position:"absolute",left:e,top:g}));f.parallax&&(e=0<v&&q.position().left+q.width()>e+m.width()?q.position().left+q.width():
e+m.width(),g=0<v&&q.position().top+q.height()>g+m.height()?q.position().top+q.height():g+m.height(),m.parent().width(e).height(g));c.fadeIn();a[v+1]&&l(v+1);b.trigger("COMPLETE_ITEM",v);c.data("active")&&h(v)};this.select=h;f=$.extend(!0,{},{css:{core:{position:"absolute",zIndex:2},parallax:{core:{position:"absolute",zIndex:1},holder:{top:0,left:0,position:"absolute",zIndex:2}}},height:null,limit:0,margin:5,overflow:!1,path:"",parallax:{},text:!1,width:null},e);b=$("<div/>").appendTo(f.target||"body").addClass(["nav",
f.text?"txt":"img"].join(" "));a=[];(function(c){var e,h;f.parallax&&(d=$("<div/>").prependTo(b).addClass("holder"),e=$.extend(!0,{rectangle:{x:0,y:0},target:d},f.parallax),h=$.extend({},f.css&&f.css.parallax&&f.parallax.core?f.parallax.core:null,{width:e.rectangle.width,height:e.rectangle.height}),$("<div/>").prependTo(b).addClass("parallax").css(h),new plura.fx.Parallax(e),f.css&&(d.css(f.css.parallax.holder),f.overflow||b.css({overflow:"hidden",width:e.rectangle.width,height:e.rectangle.height})));
for(e=0;e<c.length;e+=1)f.text?$("<a/>").appendTo(d||b).addClass("item i"+e).data({index:e}).html(e+1).click(k):(a[e]=$(new Image).data({index:e}).hide().load(m),0===e&&l(e))})(f.data);f.css&&b.css(f.css.core);this.core=b;return this});
plura.obj(".layout.ProgressBar",function(e){var c,b,d;this.refresh=function(a){b.height(c.height()).width(c.width()*a/100).show();100===a&&d.hide&&c.stop().fadeOut("slow")};this.reset=function(){b.fadeIn()};d=$.extend(!0,{},{bottom:!0,css:{core:{width:200,height:20,border:"2px solid #000"},bar:{backgroundColor:"#000"}},hide:!1,horizontal:!0,target:null},e);c=$("<div/>").appendTo(d.target||"body").addClass("plura progress").css(d.css.core);b=$("<div/>").appendTo(c).addClass("bar").css(d.css.bar).hide();
(function(a){a.height(a.height()-2*parseInt(a.css("border-top-width"),10)).width(a.width()-2*parseInt(a.css("border-top-width"),10))})(c);this.core=c;this.bar=b});
plura.obj(".layout.Refresh",function(e){var c,b,d=0,a,f,g=function(a){var d=b.format?b.format(a):a;b.fade?c.fadeOut(b.speed,function(){$(this).html(d).fadeIn(b.speed)}):c.html(d);c.trigger("CHANGE");b.refresh&&(clearInterval(f),f=setInterval(l,b.time))},h=function(a,c){var d,e=[],h;for(d in b.data)b.data.hasOwnProperty(d)&&(h=Math.floor(d/c),e[h]=e[h]||[],e[h].push(a[d]));return e},l=function(){"string"===typeof b.data?b.json?$.getJSON(b.data,null,function(a){g(a)}):$.get(b.data,null,function(a){g(a)}):
"object"===typeof b.data&&(g(a[d%a.length]),d+=1)};b=$.extend(!0,{},{data:!1,fade:!0,format:null,json:!1,limit:1,refresh:!0,speed:"slow",target:null,time:1E4},e);c=$("<div/>").appendTo(b.target||"body").addClass("refresh core");"object"===typeof b.data&&(a=h(b.data,b.limit));l()});
plura.obj(".layout.Slideshow",function(e){var c={auto:!0,cache:!1,center:!1,controls:!1,css:{core:{position:"relative"},media:{core:{position:"relative"},item:{position:"absolute"}}},data:null,height:null,id:"",inline:!1,loop:0,navigation:{},outside:!1,path:"",resize:!1,target:null,timer:8E3,width:null,video:null},b,d,a,f=0,g,h,l,k,m,n,p,r,t=this,q=function(b){p&&clearTimeout(p);l&&l.core.remove();var c=[],e;for(e=0;e<b.length;e+=1)"string"===typeof b[e]?c.push({file:b[e]}):c.push(b[e]);a=c;1<a.length&&
(k.navigation&&(l=new plura.layout.navigation.Nav($.extend(!0,{data:a,path:k.path,target:d},k.navigation)),t.navigation=l,l.core.on("COMPLETE_ITEM SELECT",A)),k.swipe&&(n=new plura.events.Touch($.extend({target:h},"object"===typeof k.swipe?k.swipe:null)),n.core.on("TOUCHMOVE TOUCHSWIPE",B)));v(f,!0)},v=function(c,e){e&&(void 0!==b&&b.removeClass("active").addClass("inactive").fadeOut(function(){$(this).remove()}),f=c,b=w(a[f]).addClass("item active i"+f),d.trigger("CHANGE",{index:f}),l&&l.select(f),
k.css&&b.css(k.css.media.item))},w=function(a){var b=a.data&&a.file,c=b?$("<div/>").addClass("mixed").appendTo(h):h,d,e;if(k.inline)h.css("background-image","url('"+x(a)+"')"),clearTimeout(p),p=setTimeout(u,k.timer);else if(a.data&&(d=$("<div/>").html(a.data).appendTo(c).addClass("data").hide().fadeIn()),a.file)if(a.file.match(/\.(gif|jpg|png)$/i)||a.type&&a.type.match(/image/i))a=x(a),d=$(new Image).load(z).appendTo(c).prop({src:a}).hide();else if(a.file.match(/\.(mp4)$/i)||a.type&&a.type.match(/video/i))e=
new plura.media.Video($.extend({src:x(a,!1),target:c},k.video)),d=e.core.on("METADATA",C);return $(b?c:d).data({video:e||!1})},u=function(){!1!==k.loop&&k.loop!==g||f!==a.length-1?(v(f<a.length-1?f+1:0,!0),0===f&&(g=(g||0)+1,d.trigger("LOOP"))):d.trigger("SEQUENCE_COMPLETE")},y=function(){v(0<f?f-1:a.length-1,!0)},x=function(a,b){var c=(k.path||"")+(a.path||"")+a.file;if(b||k.cache&&!1!==b)c+="?"+(new Date).getTime();return c},z=function(b){b=$(b.target).css({width:"auto",height:"auto"}).fadeIn();
if(k.resize||k.center){var c=b.height(),e=k.resize&&k.resize.target?k.resize.target.height():k.height||h.height(),f=b.width(),g=k.resize&&k.resize.target?k.resize.target.width():k.width||h.width();k.resize&&(k.outside&&(f>e||c>e)||!k.outside)&&("function"===typeof k.resize?k.resize(b):plura.fx.Resize({center:"boolean"===typeof k.resize||void 0===k.resize.center?!1:k.resize.center,inside:"boolean"===typeof k.resize||void 0===k.resize.inside?!0:k.resize.inside,obj:b,target:{width:g,height:e}}));k.center&&
plura.fx.Center({target:{width:g,height:e},obj:b})}!m&&1<a.length&&(clearTimeout(p),p=setTimeout(u,k.timer));d.trigger("COMPLETE_ITEM",b)},C=function(a){a.stopImmediatePropagation();d.trigger("COMPLETE_ITEM",$(a.target))},A=function(a,b){a.stopImmediatePropagation();switch(a.type){case "SELECT":b.index!==f&&v(b.index,!0)}d.trigger("NAVIGATION_"+a.type,b)},B=function(a,c){a.stopPropagation();var d;switch(a.type){case "TOUCHMOVE":b.css({left:-c.delta.x});break;case "TOUCHSWIPE":d=c.direction&&c.direction.match(/(left|right)/)?
("left"===c.direction?-1:1)*b.outerWidth():0,b.animate({left:d},"slow"),"left"===c.direction?u():"right"===c.direction&&y()}},D=function(){};this._index=function(a){if(void 0===a)return f;v(a,!0)};this._items=function(b){if(void 0===b)return a;q(b)};this.next=u;this.pause=function(a,c){clearTimeout(p);var d=void 0!==a?a:!m;d?d&&c&&b.data("video")&&b.data("video").pause(!0):p=setTimeout(u,k.timer);m=d};this.previous=y;(function(){k=$.extend({},c,e);d=$("<div/>").appendTo(k.target||"body").addClass("plura slideshow "+
k.id);h=$("<div/>").appendTo(d).addClass("media");m=!k.auto;"string"===typeof k.data?$.getJSON(k.data,function(a){q(a)}):k.data&&"object"===typeof k.data&&q(k.data);k.css&&(d.css(k.css.core),h.css(k.css.media.core));k.inline&&"boolean"!==typeof k.inline&&h.css(k.inline);t.core=d;t.media=h;r=plura.layout.Slideshow;r.items=r.items||[];r.stop=r.stop||D;r.items.push(t)})();return this});
(function(){Object.defineProperties(plura.layout.Slideshow.prototype,{index:{get:function(){return this._index()},set:function(e){this._index(e)}},items:{get:function(){return this._items()},set:function(e){this._items(e)}}})})();
plura.obj(".layout.Social",function(e){var c,b=function(a){var b=$("<div/>").appendTo(c).addClass("fb-like"),d=[];a=$.extend(!0,{},a,{height:"button_count"===a.layout?21:"box_count"===a.layout?65:a.show_faces?80:35,href:a.href||window.location.href});for(var e in a)a.hasOwnProperty(e)&&d.push(e+"="+(a[e]||""));$("<iframe/>").appendTo(b).css({width:a.width,height:a.height,border:"none",overflow:"hidden"}).prop({allowTransparency:"true",frameborder:0,scrolling:"no",src:"//www.facebook.com/plugins/like.php?"+
d.join("&")})},d=function(a){var b=$("<div/>").appendTo(c).addClass("twitter"),d=$("<a/>").appendTo(b).prop({href:"http://twitter.com/share"}).addClass("twitter-share-button").html("Tweet"),e=document.createElement("script"),l;for(l in a)a.hasOwnProperty(l)&&("related"===l?a[l].user&&d.attr("data-"+l,a[l].user+(a[l].text?":"+a[l].text:"")):a[l]&&d.attr("data-"+l,a[l]));$(e).attr({type:"text/javascript",src:"http://platform.twitter.com/widgets.js"}).appendTo(b)};c=$("<div/>").addClass("share");e=$.extend(!0,
{},{like:{action:"like",colorsheme:"light",font:null,href:null,layout:"standard",show_faces:!0,width:450},twitter:{count:"horizontal",related:{text:null,via:null},text:null,via:null,url:null},target:null},e);e.target&&c.appendTo(e.target);e.like&&b(e.like);e.twitter&&d(e.twitter);return c});
plura.obj(".layout.Table",function(e){var c,b,d=function(b){a();var d,h,l=[],k={};for(d in b[0])b[0].hasOwnProperty(d);for(d=0;d<b.length;d+=1)for(h in b[d])b[d].hasOwnProperty(h)&&(l[d]=l[d]||[],k[h]=k[h]||{rowspan:1},e&&e.merge&&0<d&&b[d][h]===b[d-1][h]&&("string"===typeof e.merge?(new RegExp(e.merge)).test(h):1)?(k[h].rowspan+=1,l[k[h].r][k[h].c].rowspan=k[h].rowspan):(k[h]={rowspan:1,r:d,c:l[d].length},l[d].push({value:b[d][h],span:k[h].rowspan})));var m,k=$("<table/>").appendTo(c);for(h=0;h<
l.length;h+=1)for(d=$("<tr/>").appendTo(k),b=0;b<l[h].length;b+=1)m=$("<td/>").appendTo(d).html(l[h][b].value||l[h][b]),l[h][b].rowspan&&1<l[h][b].rowspan&&m.prop({rowspan:l[h][b].rowspan})},a=function(){c.empty()};this.refresh=d;this.empty=a;b=$.extend(!0,{},{limit:0,merge:!0,target:null},e);this.core=c=$("<div/>").appendTo(b.target||"body").addClass("table core "+(b.classes||""));b.data&&d(b.data);return this});
plura.obj(".media.Audio",function(e){var c,b,d,a,f,g,h=function(b){(a=void 0===b?!a:b)?c.find(".play").removeClass("active").html(d.labels.play):c.find(".play").addClass("active").html(d.labels.pause);f?f.pause(a):a||f||p()},l=function(a){var d=$("<div/>").attr({id:"plura_media_audio_"+b}).appendTo(c);a={content:a,id:b,obj:"plura.media.Audio",type:"audio"};swfobject.embedSWF(plura.constants.Paths.SWF,d.attr("id"),"0","0","10.0.0",null,a,null,null,m)},k=function(b){h(!a)},m=function(a){f=swfobject.getObjectById(a.id)},
n=function(a){for(var b in g.instances)g.instances.hasOwnProperty(b)&&!b.match("i"+a)&&g.instances[b].pause(!0)},p=function(){d.data?l(d.data):d.path&&$.get(d.path,function(a){console.log(a);l(a)})};this.fade=function(a){c.find(".menu").fadeIn("slow")};this.pause=h;g=plura.media.Audio;g.count=void 0===g.count?0:g.count+1;g.instances=g.instances||{};g.instances["i"+g.count]=this;g.pause=g.pause||n;b=g.count;d=$.extend(!0,{},{auto:!0,data:null,controls:!0,css:{flash:{position:"relative",height:0,width:0},
test:{position:"absolute",zIndex:1E3,width:400,height:400}},fade:!0,labels:{pause:"Pause",play:"Play"},path:null,params:null,target:"body",test:!1},e);(function(){c=$("<div/>").appendTo(d.target).addClass("p audio").css({position:"relative"});var a=$("<ul/>").appendTo(c).addClass("menu controls");d.controls&&$("<li/>").appendTo(a).click(k).addClass("play");h(!d.auto)})();this.core=c});
plura.obj(".media.Video",function(e){var c,b,d=!0,a,f,g=this,h=function(b){a.empty();var c,d=b instanceof Array?b:[b],e;for(b=0;b<d.length;b+=1)c=d[b].src||d[b],e=d[b].type||"video/"+c.match(/\.([^.]+)$/)[1],$("<source/>").prop({src:c,type:e}).appendTo(a);return g},l=function(c){(d=void 0===c?!d:c)?(b.addClass("pause"),a[0].pause()):(b.removeClass("pause"),a[0].play())},k=function(b){void 0!==b&&(a[0].volume=b);return a[0].volume},m=function(a){a.stopImmediatePropagation();l()};this.pause=l;this.prop=
function(b){a.prop(b);return g};this.src=h;this.volume=k;c=new plura.net.Client;e=$.extend(!0,{},{autoplay:!0,controls:!0,pause:!0,preload:!0,loop:!0,wrap:!1},e);f={autoplay:e.autoplay,controls:e.controls,loop:e.loop,height:e.height,preload:e.preload,width:e.width,poster:e.poster};a=$("<video/>").prop(f).on("loadedmetadata",function(a){b.trigger("METADATA",{width:this.videoWidth,height:this.videoHeight})});b=e.wrap?$("boolean"===typeof e.wrap?"<div/>":e.wrap).append(a).addClass("video"):a;b.appendTo(e.target||
"body");e.src&&h(e.src);g.core=b;if(e.pause&&!e.controls||c.data.ios)a.on("click touchstart",m),e.wrap&&b.click(m);e.volume&&k(e.volume);c.data.ios||l(!e.autoplay);return this});
plura.obj(".net.Client",function(e){var c;c=navigator.userAgent;var b=Boolean(c.match(/Android/i)),d=Boolean(c.match(/(explorer|MSIE)/i)),a=Boolean(c.match(/iPad/i)),f=Boolean(c.match(/iPhone/i)),g=Boolean(c.match(/iPod/i)),f=f?"iPhone":a?"iPad":g?"iPod":null,h=Boolean(null===document.location.href.match(/https?:\/\//)),l=Boolean(f||b||c.match(/Windows.+Touch/i)),k=parseInt(navigator.appVersion,10);d&&(k=parseInt(navigator.appVersion.match(/msie ([0-9\.]+)/i)[1],10));c={agent:c,android:b,ie:d,ios:f,
ipad:a,ipod:g,offline:h,touch:l,version:k};b=[];a=e&&e.ie?e.ie:11;if(c.ie){if(b.push("ie","ie"+c.version),c.version<a)for(b.push("ie_lte"+c.version),d=c.version;d<a;d+=1)b.push("ie_lt"+(d+1))}else c.ios?b=b.concat(["ios",c.ios.toLowerCase()]):c.android&&b.push("android");c.offline&&b.push("offline");b.push((c.touch?"":"no-")+"touch");c.classes=b;this.data=c;e&&e.classes&&$("body").addClass(c.classes.join(" "))});
plura.obj(".net.URLManager",function(e){var c={analytics:!0,lang:!0,separator:"#"},b,d,a,f,g,h,l=function(a,b,c,d,e){window._gaq&&(a=["_trackEvent",a,b,c,d],void 0!==e&&!0===e&&a.push(e),_gaq.push(a))},k=function(a){var c=[];a&&b&&c.push(b);g&&c.push(g);return c.join("/")},m=function(a){void 0!==a&&a!==g&&(g=a,d.push(g));window.location.href="#!/"+k(!0);f.analytics&&(a="/"+k(!0),window._gaq&&_gaq.push(["_trackPageview",a]))};this._history=function(){return d};this._index=function(){return a};this._lang=
function(a){void 0!==a&&(b=a,m());return b};this._path=function(a){void 0!==a&&m(a);return g};this._root=function(){return h};this._url=function(){return h+"#!/"+k(!0)+"/"};this.event=function(){l.apply(null,arguments)};this.perma=function(a){return a.match(h+".*?([^=]*[^/])/?$")[1]};(function(){var k=window.location.href;f=$.extend(!0,{},c,e);d=[];a=0;h=k.match(/[^#]+/)[0];k.match(/#!\/(.+)/)&&(k=k.match(/#!\/(.+)/)[1].replace(/\/$/,"").split(/\//),f.lang&&k[0].match(/^[a-z]{2}$/)&&(b=k.shift()),
g=k.join("/"),d.push(g))})()});(function(){Object.defineProperties(plura.net.URLManager.prototype,{history:{get:function(){return this._history()}},index:{get:function(){return this._index()}},lang:{get:function(){return this._lang()},set:function(e){this._lang(e)}},path:{get:function(){return this._path()},set:function(e){this._path(e)}},root:{get:function(){return this._root()}},url:{get:function(){return this._url()}}})})();
plura.obj(".templates.alert.Slide",function(e){var c,b;this.refresh=function(d,a){clearTimeout(b);c.html(a).stop(!0,!0).slideDown().addClass(d?"success":"error").removeClass(d?"error":"success");b=setTimeout(function(){c.slideUp()},2E3)};c=$("<p/>").appendTo(e.target||"body").addClass("alert").hide()});
plura.obj(".templates.checkout.end.Form",function(e){var c;this._items=function(b){c.params={items:b}};e=$.extend(!0,{},{labels:{check:{email:{empty:"Please insert your email. Thank you!",invalid:"Your email address is invalid."},name:"Please insert your first and last name. Thank you!",message:"Please include a message. Thank you!"},fields:{email:"Email",name:"Name",message:"Message"}}},e);c=new plura.form.Form({check:[{id:"user_email",rules:[{alert:e.labels.check.email.empty},{exp:String(plura.constants.RegExp.EMAIL),
alert:e.labels.check.email.invalid}]},{id:"user_message",alert:e.labels.check.message},{id:"user_name",alert:e.labels.check.name}],fields:[[{name:"user_name",label:e.labels.fields.name},{name:"user_email",label:e.labels.fields.email},{name:"user_message",type:"textarea",label:e.labels.fields.message}]],params:$.extend({type:"checkout"},e.params),reset:!0,target:e.target});c.core.on("FORM_PROCESS_ERROR FORM_PROCESS_SUCCESS FORM_VALIDATION_ERROR",function(b,c){switch(b.type){case "FORM_PROCESS_ERROR":alert(c.alert);
break;case "FORM_PROCESS_SUCCESS":alert(c.alert);break;case "FORM_VALIDATION_ERROR":alert(c.alert)}}).addClass("big check-out");this.core=c.core});(function(){Object.defineProperties(plura.templates.checkout.end.Form.prototype,{items:{set:function(e){this._items(e)}}})})();
plura.obj(".templates.checkout.end.List",function(e){var c,b,d;this.refresh=function(a){var b,e,h,l=$("<ul/>").addClass("items");c.empty().append(l).prepend(d);for(b=0;b<a.length;b+=1){e=a[b];var k=$("<li/>").addClass("group");$("<span/>").text(e.name).addClass("group-label").appendTo(k);$("<ul/>").appendTo(k).addClass("group-items");e=k.appendTo(l);for(h in a[b].items)if(a[b].items.hasOwnProperty(h)){var k=a[b].items[h],m=$("<li/>").addClass("item item-"+k.data.ID),n=$("<ul/>").addClass("subitems").appendTo(m);
$("<li/>").addClass("icon").css("background-image","url("+k.data.img.dark+")").appendTo(n);$("<li/>").addClass("label").appendTo(n).html(k.data.title);m.appendTo(e)}}};b=$.extend(!0,{},{labels:{title:"List"}},e);c=$("<div/>").appendTo(e.target).addClass("list");d=$("<div/>").addClass("title").text(b.labels.title);this.core=c});(function(){Object.defineProperties(plura.templates.checkout.end.List.prototype,{items:{set:function(e){this.refresh(e)}}})})();
plura.obj(".templates.checkout.End",function(e){var c,b,d;this._items=function(a){void 0!==a&&(c.items=a,d.list&&(b.items=a))};d=$.extend(!0,{},{list:!0},e);e=$("<div/>").addClass("checkout-end");c=new plura.templates.checkout.end.Form({path:d.process,params:d.params,target:e});d.list&&(b=new plura.templates.checkout.end.List($.extend({target:e},d.list)));this.core=e;this.form=c;this.list=b});
(function(){Object.defineProperties(plura.templates.checkout.End.prototype,{items:{get:function(){return this._items()},set:function(e){this._items(e)}}})})();
plura.obj(".templates.Checkout",function(e){var c,b,d,a;d=$.extend(!0,{},{end:!0,labels:{sequence:{end:"Checkout"}}},e);c=$("<div/>").appendTo(e.target).addClass("checkout");a=new plura.templates.Sequence({items:function(){var a;d.end&&(b=new plura.templates.checkout.End(d.end),a=[{name:"end",label:d.labels.sequence.end,obj:b}]);return e.sequence?e.sequence.concat(a):a}(),parent:d.parent,target:c});a.core.on("CHANGE COMPLETE COMPLETE_ITEM EXIT",function(d,e){d.stopImmediatePropagation();switch(d.type){case "COMPLETE":var h,
l;if(1<a.items.length)for(l=[],h=0;h<a.items.length-1;h+=1)a.items[h].obj.cart&&l.push({name:a.items[h].name||"i"+h,items:a.items[h].obj.cart.items});b.items=l;break;case "EXIT":c.trigger("EXIT")}});this.core=c;this.sequence=a});
plura.obj(".templates.sequence.Breadcrumbs",function(e){var c,b,d,a,f=function(){c.trigger("PARENT")},g=function(a){c.trigger("SEQUENCE",$(a.target).data("index"))};this.refresh=function(a){var b,c;for(b=0;b<a.items.length;b+=1)c=[],d[b].off("click",g).removeClass("active completed disabled enabled"),a.items[b].completed||!b||b&&a.items[b-1].completed?(a.items[b].completed?c.push("completed"):c.push("enabled"),d[b].click(g)):c.push("disabled"),a.index===b&&c.push("active"),d[b].addClass(c.join(" "))};
b=$.extend(!0,{},{},e);c=$("<div/>").appendTo(b.target).addClass("breadcrumbs");(function(){var e;c.empty();d=[];b.parent&&$("<div/>").addClass("breadcrumbs-parent").text(b.parent).appendTo(c).click(f);a=$("<div/>").addClass("breadcrumbs-sequence-items").appendTo(c);for(e=0;e<b.items.length;e+=1)d[e]=$("<div/>").addClass("breadcrumbs-sequence-item breadcrumbs-sequence-item-"+e).text(b.items[e].label||e).data("index",e).appendTo(a)})();this.core=c});
plura.obj(".templates.sequence.PreviousNext",function(e){var c,b,d,a,f=function(a){a.stopImmediatePropagation();c.trigger("NEXT")},g=function(a){a.stopImmediatePropagation();c.trigger("PREVIOUS")},h=function(a){a.stopImmediatePropagation();c.trigger("PARENT")};this.refresh=function(b){a.off("click",g).off("click",h);d.off("click",f);if(!b.index&&e.parent||0<b.index)a.addClass("active").on("click",b.index?g:h);else a.removeClass("active");b.index<b.items.length-1&&b.items[b.index].completed?d.on("click",
f).addClass("active"):d.removeClass("active")};b=$.extend(!0,{},{},e);c=$("<div/>").appendTo(b.target).addClass("previous-next");d=$("<div/>").appendTo(c).addClass("previous-next-item next");a=$("<div/>").appendTo(c).addClass("previous-next-item previous");this.core=c});
plura.obj(".templates.Sequence",function(e){var c={chained:!0,navigation:{breadcrumbs:!0,previous_next:!0}},b,d,a,f,g,h,l,k,m,n=this,p=function(b){b!==a&&(f=a,a=b,r())},r=function(){var c;c=void 0===g[a].obj.completed||g[a].obj.completed;if(g[a].completed=c)b.trigger("COMPLETE_ITEM",{index:a}),a===g.length-1&&b.trigger("COMPLETE");else if(h.chained)for(c=a+1;c<g.length;c+=1){var d=c;g[d].completed=!1;"function"===typeof g[d].obj.reset&&g[d].obj.reset()}for(c=0;c<g.length;c+=1)d=[],g[c].obj.core.removeClass("active completed disabled enabled"),
g[c].completed||!c||c&&g[c-1].completed?void 0===g[c].obj.completed||g[c].obj.completed?d.push("completed"):d.push("enabled"):d.push("disabled"),a===c&&d.push("active"),g[c].obj.core.addClass(d.join(" "));void 0!==f&&b.removeClass("sequence-"+f);b.addClass("sequence-"+a);m&&m.refresh({index:a,items:g});k&&k.refresh({index:a,items:g})},t=function(a,c){a.stopImmediatePropagation();switch(a.type){case "PARENT":b.trigger("EXIT");break;case "SEQUENCE":p(c)}},q=function(c){c.stopImmediatePropagation();
switch(c.type){case "PARENT":b.trigger("EXIT");break;case "NEXT":p(a+1);break;case "PREVIOUS":p(a-1)}},v=function(a,b){a.stopImmediatePropagation();r(b)};this._items=function(){return g};(function(){h=$.extend(!0,{},c,e);b=$("<div/>").appendTo(h.target).addClass("sequence");if(h.navigation){l=$("<div/>").appendTo(b).addClass("sequence-nav");var a={target:l,items:h.items,parent:h.parent};h.navigation.breadcrumbs&&(k=new plura.templates.sequence.Breadcrumbs($.extend(!0,{},h.navigation.breadcrumbs,a)),
k.core.on("PARENT SEQUENCE",t));h.navigation.previous_next&&(m=new plura.templates.sequence.PreviousNext($.extend(!0,{},h.navigation.previous_next,a)),m.core.on("PARENT NEXT PREVIOUS",q))}var a=h.items,f;if(g){for(f=0;f<g.length;f+=1)g[f].obj.core.off("REFRESH",v).removeClass("completed");g=null}d&&d.remove();var y;d=$("<div/>").appendTo(b).addClass("sequence-items");g=[];for(f=0;f<a.length;f+=1)y=a[f].obj?a[f]:{obj:a[f]},g[f]=y,g[f].obj.core.appendTo(d).addClass("sequence-item").on("REFRESH",v);
p(0);n.core=b})()});(function(){Object.defineProperties(plura.templates.Sequence.prototype,{items:{get:function(){return this._items()}}})})();
plura.obj(".templates.structures.Content",function(e){var c,b,d,a=function(d,e){var k="string"===typeof d?g(d):d,m=void 0===e?!0:e;m&&(!m||c&&c[0]===k[0])||f(k,m);!m||c&&c[0]===k[0]||(c&&a(c,!1),c=k,b.trigger("REFRESH",k.data()))},f=function(a,b){!0===b?a.stop(!0).fadeIn().addClass("active"):a.stop(!0).fadeOut(function(){$(this).hide()}).removeClass("active")},g=function(a){a="object"===typeof a?a:{id:a};var c=[a.id,a.vanity||"",a.classes||""].join(" "),c=d[a.id]||$("<div/>").addClass("holder "+c).append(a.obj||
null).data(a).appendTo(b).hide();return d[a.id]=c};this.activate=a;this.disable=function(){c&&(a(c,!1),c=null)};this.get=g;e=$.extend(!0,{},{},e);b=$("<div/>").appendTo(e.target||"body").addClass(["content",e.classes||""].join(" "));d={};this.core=b;this.tree=d;return this});
plura.obj(".templates.structures.menu.MenuConverter",function(e){var c,b,d=function(c,e){var k,m,n,p,r,t,q;t=c.children("li");for(n=0;n<t.length;n+=1)r=t.eq(n),p=e?e+"_"+n:"i"+n,m={depth:p.split("_").length-1,id:p,label:r.children("a").html()},k=p+" node",q=r.children("a").click(g).addClass("trigger"),b[p]=r,r.children("ul").length?(q.click(a),d(r.children("ul"),p)):r.click(f),r.data(m).addClass(k)},a=function(a){c.trigger("_OPEN",$(a.currentTarget).parent())},f=function(a){c.trigger("_SELECT",$(a.currentTarget))},
g=function(a){a.preventDefault()};c=e.target.on("_OPEN _SELECT",e.handler);this.tree=b={};d(c)});
plura.obj(".templates.structures.Menu",function(e){var c,b,d,a,f=this,g=function(e,f){var h=void 0===f?!0:f;if(!h||c&&c[0]===e[0]){if(h)return;c=null}else c&&g(c,!1),c=e;var k="selected selected-"+e.data("id");h?(b.addClass(k),e.addClass("active")):(b.removeClass(k),e.removeClass("active"));var k=e.data("id").replace(/i(.+)/,"$1").split("_").slice(0,-1),l,m;if(k.length)for(l=0;l<k.length;l+=1)m="i"+k.slice(0,l?-l:k.length).join("_"),h?(0===l&&a[m].addClass("parent"),a[m].addClass("ancestor ancestor-"+
l)):h||(0===l&&a[m].removeClass("parent"),a[m].removeClass("ancestor ancestor-"+l));if(h){if(d.url){k=e.data();h=r(k);k=[k];l=[];h&&(k=h.concat(k));for(h=0;h<k.length;h+=1)l.push(k[h].vanity||k[h].id);url.path=l.join("/")}b.trigger("SELECT",e.data())}},h=function(c,e){var f,g,k=c.data("id").replace(/i(.+)/,"$1").split("_");if(void 0===e?!c.hasClass("open"):e){d.close&&b.find(".open").each(function(a){$(this).data("id").match(c.data("id"))||h($(this),!1)});for(f=0;f<k.length;f+=1)g="i"+k.slice(0,f?
-f:k.length).join("_"),a[g].addClass("open");b.trigger("OPEN",c.data())}else c.removeClass("open")},l=function(a){return d.leaf?d.leaf(a):a.children?!1:!0},k=function(a){return d.trigger?d.trigger(a):$("<a/>").prop({href:"#"}).html(a.label).click(function(a){a.preventDefault()})},m=function(c,e,h){var f,g,n,p;for(g=0;g<c.length;g+=1)n=h?h+"_"+g:"i"+g,p={data:c[g],depth:n.split("_").length-1,id:n,label:c[g].label||c[g].name||c[g].vanity||c[g].id||("string"===typeof c[g]?c[g]:n),vanity:c[g].id||c[g].vanity||
null},f=n+" node"+(p.vanity?" id-"+p.vanity:"")+(c[g][d.nodeID]?" id-"+c[g][d.nodeID]:""),f=$(d.tags.leaf||d.tags).appendTo(e).data(p).addClass(f),p=k(p).appendTo(f).addClass("trigger"),a[n]=f,l(c[g])?(f.click(u).addClass("leaf"),b.trigger("COMPLETE_ITEM",f.data())):(p.click(w),f=$(d.tags.branch||d.tags).appendTo(f).addClass("branch"),m(c[g].children,f,n))},n=function(c){b.empty();a={};f.tree=a;d.data=c;m(d.data,b);d.first&&q(d.first);b.trigger("COMPLETE")},p=function(b){var d;if(void 0===b||"boolean"===
typeof b){if(c)return c;for(d in a)if(a.hasOwnProperty(d)&&l(a[d].data("data")))return a[d]}else{if("string"===typeof b)return a[b];if("number"===typeof b)return a["i"+b]}},r=function(b){var c,d,e=b.id.split("_");if(1<e.length){c=[];for(b=1;b<e.length;b+=1)d=e.slice(0,b?-b:e.length).join("_"),c.push(a[d].data());c=c.reverse()}return c},t=function(c){var d=new plura.templates.structures.menu.MenuConverter({handler:v,target:c});b=c;a=d.tree;f.tree=a},q=function(a){a=p(a);g(a)},v=function(a,b){a.stopImmediatePropagation();
switch(a.type){case "_OPEN":h($(b));break;case "_SELECT":g($(b))}},w=function(a){h($(a.currentTarget).parent())},u=function(a){g($(this))};this.activate=g;this.ancestors=r;this.disable=function(){if(c){var a=c.data();g(c,!1);b.trigger("UNSELECT",a)}};this.get=p;this.refresh=n;this.select=q;d=$.extend(!0,{},{close:!0,data:null,first:!1,id:"",leaf:null,nodeID:"nodeID",object:null,tags:{branch:"<ul/>",leaf:"<li/>"},url:null},e);d.object?t(d.object):(b=$(d.tags.branch||d.tags).appendTo(d.target||"body"),
d.data&&n(d.data));f.core=b.addClass("menu "+d.id)});
plura.obj(".templates.structures.Tabs",function(e){var c,b,d,a,f=function(a){a=b.tree[a]?b.tree[a].data():"object"===typeof a?a:{id:a};return d.get({classes:g(a.id).join(" "),id:a.id,vanity:a.vanity})},g=function(a){var b=[],c=a.split("_").slice(0,-1);for(a=0;a<c.length;a+=1)b[a]=a?b.join("_")+"_"+c[a]:c[a].replace(/i/,"p");return b};this.disable=function(){b.disable();d.disable()};this.get=f;this.refresh=function(){b.refresh(a.tree)};this.select=function(a){b.select(a)};a=$.extend(!0,{},{first:!1,
delay:!1,id:null,menu:{},tree:null},e);c=$("<div/>").appendTo(a.target||"body").addClass("plura templates tabs core "+(a.id||""));b=new plura.templates.structures.Menu($.extend(!0,{},a.menu,{target:c,first:a.first}));b.core.on("COMPLETE COMPLETE_ITEM OPEN SELECT",function(a,b){a.stopPropagation();if("SELECT"===a.type){var e=f(b.id);d.activate(e)}c.trigger("MENU_"+a.type,b)});this.content=d=new plura.templates.structures.Content({target:c});this.core=c;this.menu=b;return this});
plura.obj(".utils.Cache",function(e){var c=(new Date).getTime();e+=e.match(/\?/)?e.match(/\&$/)?"":"&":"?";return e+c});plura.obj(".utils.Extend",function(e,c){function b(){}b.prototype=new e;c.prototype=new b;return c});
plura.obj(".utils.Flat",function(e,c,b){var d=[],a,f=c||{},g,h=plura.utils.Flat;for(a in e)if(e.hasOwnProperty(a))if(e[a]instanceof Array)for(c=0;c<e[a].length;c+=1)if("object"===typeof e[a][c]&&!(e[a][c]instanceof Array))d=d.concat(h(e[a][c],f,a));else{if("number"===typeof e[a][c]||"string"===typeof e[a][c])g=$.extend({},f),g[a]=e[a][c],d.push(g)}else"object"===typeof e[a]&&(f[b]=a,d=d.concat(h(e[a],f)));return d});
plura.obj(".utils.Hidden",function(e){var c=(new Date).getTime(),b=function(b){e.parents("body *").each(function(){$(this).is(":animated")||(!b&&void 0!==b||"none"!==$(this).css("display")?!1===b&&$(this).hasClass("i"+c)&&$(this).removeClass("i"+c).hide():$(this).addClass("i"+c).show())})};this.get=function(){b();var c={width:e.width(),height:e.height(),innerWidth:e.innerWidth(),innerHeight:e.innerHeight(),outerWidth:e.outerWidth(),outerHeight:e.outerHeight()};b(!1);return c};this.show=b});
plura.obj(".utils.String",{path:function(e,c){var b=[],d,a,f,g;d=function(a){a.match(/^https?:\/\//)||(a=window.location.href.replace(/[^\/]+$/,"")+a);return a};e=d(e);c=c?d(c):window.location.href;c.match(/^http/)&&(f=c.replace(/(https?:\/\/)(.+)(\/([^\/]+)?)$/g,"$1$2").split("/"));a=f.length;for(d=0;d<a;d+=1){if(e.match(f.join("/"))){g=e.replace(f.join("/"),"");break}f.splice(-1);b.push("..")}return b.join("/")+g},test:function(e,c){var b,d,a;b=e instanceof Array?e:[e];for(d=0;d<b.length;d+=1)if(a=
"string"===typeof b[d]?new RegExp(b[d].replace(/^(\/)(.*)(\/)$/,"$2")):b[d],!a.test(c))return!1;return!0}});